from django.db import models
from django.template.defaultfilters import default

# Create your models here.

class dct_t_l3f11faam_type_sheet(models.Model):
    sid=models.AutoField(primary_key=True)
    pjcode=models.CharField(max_length=10,default="HYGS")
    typecode=models.CharField(max_length=10,null=True,blank=True,unique=True)
    applenum=models.IntegerField(default=0)
    appleweight=models.DecimalField(max_digits=3,decimal_places=1)
    applegrade=models.CharField(max_length=1,null=True,blank=True)
    memo=models.CharField(max_length=50,null=True,blank=True)

class dct_t_l3f11faam_factory_sheet(models.Model):
    sid=models.AutoField(primary_key=True)
    pjcode=models.CharField(max_length=10)
    workstart=models.TimeField(null=True)
    workend=models.TimeField(null=True)
    reststart=models.TimeField(null=True)
    restend=models.TimeField(null=True)
    fullwork=models.IntegerField(default=0)
    address=models.CharField(max_length=100)
    latitude=models.IntegerField(default=0)
    longitude=models.IntegerField(default=0)
    trafficmoney=models.IntegerField(null=True)
    factorybonus=models.IntegerField(null=True)
    memo=models.TextField(null=True)

class dct_t_l3f11faam_production(models.Model):
    sid=models.AutoField(primary_key=True)
    pjcode=models.CharField(max_length=10)
    qrcode=models.CharField(max_length=50)
    owner=models.CharField(max_length=10)
    typecode=models.CharField(max_length=10)
    applyweek=models.IntegerField(null=True)
    applytime=models.DateTimeField(auto_now_add=True)
    activetime=models.DateTimeField(null=True)
    lastactivetime=models.DateTimeField(null=True)
    activeman=models.CharField(max_length=10,null=True)

class dct_t_l3f11faam_buy_consumables(models.Model):
    sid=models.AutoField(primary_key=True)
    supplier=models.CharField(max_length=50)
    contype=models.CharField(max_length=10)
    amount=models.IntegerField(default=0)
    unitprice=models.DecimalField(max_digits=10,decimal_places=3)
    totalprice=models.DecimalField(max_digits=10,decimal_places=3)
    createtime=models.DateTimeField(null=True)
    datatype=models.CharField(max_length=20)

class dct_t_l3f11faam_member_sheet(models.Model):
    mid=models.CharField(max_length=10,primary_key=True)
    pjcode=models.CharField(max_length=10)
    employee=models.CharField(max_length=10)
    gender=models.IntegerField(default=1)
    phone=models.CharField(max_length=15)
    openid=models.CharField(max_length=50,null=True)
    regdate=models.DateField(auto_now_add=True)
    position=models.CharField(max_length=10)
    zone=models.CharField(null=True,max_length=50)
    idcard=models.CharField(max_length=50,null=True)
    address=models.CharField(max_length=100,null=True)
    bank=models.CharField(max_length=10,null=True)
    bankcard=models.CharField(max_length=20,null=True)
    photo=models.CharField(max_length=15,null=True)
    unitprice=models.IntegerField(default=0)
    standardnum=models.IntegerField(default=0)
    onjob=models.BooleanField(default=True)
    memo=models.CharField(max_length=15,null=True)

class dct_t_l3f11faam_daily_sheet(models.Model):
    sid=models.AutoField(primary_key=True)
    pjcode=models.CharField(max_length=10)
    employee=models.CharField(max_length=10)
    workday=models.DateField(null=True)
    arrivetime=models.TimeField(null=True)
    leavetime=models.TimeField(null=True)
    offwork=models.DecimalField(null=True,max_digits=3,decimal_places=1)
    worktime=models.FloatField(null=True)
    unitprice=models.IntegerField(null=True)
    laterflag=models.BooleanField(default=False)
    earlyflag=models.BooleanField(default=False)
    daystandardnum=models.IntegerField(default=0)

class dct_t_l3f11faam_material_stock_table(models.Model):
    sid=models.AutoField(primary_key=True)
    stockname=models.CharField(max_length=20)
    stockaddress=models.CharField(max_length=100)
    stockleader=models.CharField(max_length=10)
    createtime=models.DateTimeField(auto_now_add=True)
    isself=models.BooleanField(default=False)
    bucketnum=models.IntegerField(default=0)
    totalprice=models.IntegerField(default=0)
    updatetime=models.DateTimeField(auto_now=True)

class dct_t_l3f11faam_material_history(models.Model):
    sid=models.AutoField(primary_key=True)
    stockid=models.CharField(max_length=10)
    stockname=models.CharField(max_length=30)
    into=models.BooleanField(default=False)
    bucketnum=models.IntegerField(null=True)
    price=models.IntegerField(null=True)
    mode=models.BooleanField(default=False)
    vendor=models.CharField(max_length=30,null=True)
    charge=models.CharField(max_length=30,null=True)
    mobile=models.CharField(max_length=15)
    trunk=models.CharField(max_length=15,null=True)
    target=models.CharField(max_length=30,null=True)
    logisitics=models.CharField(max_length=10,null=True)
    time=models.DateTimeField(auto_now=True)

class dct_t_l3f11faam_product_stock_sheet(models.Model):
    sid=models.AutoField(primary_key=True)
    stockname=models.CharField(max_length=20)
    stockaddress=models.CharField(max_length=50)
    createtime=models.DateTimeField(null=True)
    productweight=models.IntegerField(null=True,default=0)
    puoductsize=models.CharField(null=True,max_length=4)
    productnum=models.IntegerField(null=True,default=0)
    number=models.IntegerField(null=True,default=0)
    message=models.CharField(max_length=10,null=True)
    updatetime=models.DateTimeField(null=True)

class dct_t_l3f11faam_product_history(models.Model):
    sid=models.AutoField(primary_key=True)
    stockname=models.CharField(max_length=20)
    productweight = models.IntegerField(default=0,null=True,)
    puoductsize=models.CharField(null=True,max_length=4)
    productnum = models.IntegerField(default=0,null=True,)
    number = models.IntegerField(default=0,null=True,)
    containerID=models.CharField(max_length=30,null=True)
    platenumber=models.IntegerField(default=0)
    drivername=models.CharField(max_length=10)
    driverphone=models.CharField(max_length=15)
    receivingunit=models.CharField(max_length=15)
    logisticsunit=models.CharField(max_length=20)
    outtime=models.DateTimeField(auto_now=True)
    message=models.CharField(max_length=20)