# Generated by Django 2.1a1 on 2018-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF1sym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f1sym_account_secondary',
            name='openid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
