# Generated by Django 2.1a1 on 2018-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f11faam_product_stock_sheet',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('stockname', models.CharField(max_length=20)),
                ('stockaddress', models.CharField(max_length=50)),
                ('stockheader', models.CharField(max_length=10)),
                ('stocktime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
