# Generated by Django 2.1a1 on 2018-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f11faam_typesheet',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('pjcode', models.CharField(default='HYGS', max_length=10)),
                ('typecode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('applenum', models.IntegerField(default=0)),
                ('appleweight', models.IntegerField(default=0)),
                ('applegrade', models.CharField(blank=True, max_length=1, null=True)),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
