# Generated by Django 2.1.7 on 2019-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF11faam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dct_t_l3f11faam_batch_scan',
            name='owner',
            field=models.CharField(default='鏉庡潳娲�', max_length=10),
        ),
    ]
