# Generated by Django 2.1a1 on 2018-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF11faam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dct_t_l3f11faam_buy_consumables',
            name='createtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_daily_sheet',
            name='offwork',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
