# Generated by Django 2.1.1 on 2018-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF11faam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dct_t_l3f11faam_daily_sheet',
            old_name='arraytime',
            new_name='arrivetime',
        ),
        migrations.AddField(
            model_name='dct_t_l3f11faam_production',
            name='lastactivetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_member_sheet',
            name='bankcard',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_member_sheet',
            name='idcard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_member_sheet',
            name='memo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_member_sheet',
            name='openid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f11faam_member_sheet',
            name='photo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
