# Generated by Django 2.1.1 on 2018-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF11faam', '0002_dct_t_l3f11faam_batch_scan_applydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dct_t_l3f11faam_batch_scan',
            name='activetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
