# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsMainform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsMainWindow(object):
    def setupUi(self, cebsMainWindow):
        cebsMainWindow.setObjectName("cebsMainWindow")
        cebsMainWindow.resize(1202, 546)
        cebsMainWindow.setMinimumSize(QtCore.QSize(1202, 546))
        self.centralwidget = QtWidgets.QWidget(cebsMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_runProgress = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_runProgress.setGeometry(QtCore.QRect(380, 40, 761, 401))
        self.textEdit_runProgress.setMouseTracking(True)
        self.textEdit_runProgress.setTabletTracking(True)
        self.textEdit_runProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_runProgress.setAutoFillBackground(True)
        self.textEdit_runProgress.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_runProgress.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_runProgress.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_runProgress.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_runProgress.setTabChangesFocus(True)
        self.textEdit_runProgress.setObjectName("textEdit_runProgress")
        self.pushButton_ctrl_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctrl_start.setGeometry(QtCore.QRect(20, 20, 161, 71))
        self.pushButton_ctrl_start.setObjectName("pushButton_ctrl_start")
        self.label_runProgress = QtWidgets.QLabel(self.centralwidget)
        self.label_runProgress.setGeometry(QtCore.QRect(380, 20, 261, 16))
        self.label_runProgress.setObjectName("label_runProgress")
        self.pushButton_ctrl_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctrl_stop.setGeometry(QtCore.QRect(200, 20, 151, 71))
        self.pushButton_ctrl_stop.setObjectName("pushButton_ctrl_stop")
        self.pushButton_runpg_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runpg_test.setGeometry(QtCore.QRect(980, 450, 71, 41))
        self.pushButton_runpg_test.setObjectName("pushButton_runpg_test")
        self.pushButton_runpg_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runpg_clear.setGeometry(QtCore.QRect(1060, 450, 71, 41))
        self.pushButton_runpg_clear.setObjectName("pushButton_runpg_clear")
        self.pushButton_ctrl_zero = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctrl_zero.setGeometry(QtCore.QRect(20, 110, 161, 71))
        self.pushButton_ctrl_zero.setObjectName("pushButton_ctrl_zero")
        self.pushButton_cala_pilot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cala_pilot.setGeometry(QtCore.QRect(20, 200, 161, 71))
        self.pushButton_cala_pilot.setObjectName("pushButton_cala_pilot")
        self.groupBox_cala_set = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_cala_set.setGeometry(QtCore.QRect(20, 290, 341, 191))
        self.groupBox_cala_set.setObjectName("groupBox_cala_set")
        self.groupBox_cala_move_scale = QtWidgets.QGroupBox(self.groupBox_cala_set)
        self.groupBox_cala_move_scale.setGeometry(QtCore.QRect(10, 70, 311, 51))
        self.groupBox_cala_move_scale.setObjectName("groupBox_cala_move_scale")
        self.radioButton_cala_5cm = QtWidgets.QRadioButton(self.groupBox_cala_move_scale)
        self.radioButton_cala_5cm.setGeometry(QtCore.QRect(220, 20, 41, 21))
        self.radioButton_cala_5cm.setObjectName("radioButton_cala_5cm")
        self.radioButton_cala_05mm = QtWidgets.QRadioButton(self.groupBox_cala_move_scale)
        self.radioButton_cala_05mm.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.radioButton_cala_05mm.setChecked(True)
        self.radioButton_cala_05mm.setObjectName("radioButton_cala_05mm")
        self.radioButton_cala_1cm = QtWidgets.QRadioButton(self.groupBox_cala_move_scale)
        self.radioButton_cala_1cm.setGeometry(QtCore.QRect(170, 20, 41, 21))
        self.radioButton_cala_1cm.setObjectName("radioButton_cala_1cm")
        self.radioButton_cala_1mm = QtWidgets.QRadioButton(self.groupBox_cala_move_scale)
        self.radioButton_cala_1mm.setGeometry(QtCore.QRect(70, 20, 41, 21))
        self.radioButton_cala_1mm.setChecked(False)
        self.radioButton_cala_1mm.setObjectName("radioButton_cala_1mm")
        self.radioButton_cala_5mm = QtWidgets.QRadioButton(self.groupBox_cala_move_scale)
        self.radioButton_cala_5mm.setGeometry(QtCore.QRect(120, 20, 41, 21))
        self.radioButton_cala_5mm.setObjectName("radioButton_cala_5mm")
        self.groupBox_cala_move_dir = QtWidgets.QGroupBox(self.groupBox_cala_set)
        self.groupBox_cala_move_dir.setGeometry(QtCore.QRect(10, 130, 311, 51))
        self.groupBox_cala_move_dir.setObjectName("groupBox_cala_move_dir")
        self.radioButton_cala_y_plus = QtWidgets.QRadioButton(self.groupBox_cala_move_dir)
        self.radioButton_cala_y_plus.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.radioButton_cala_y_plus.setChecked(True)
        self.radioButton_cala_y_plus.setObjectName("radioButton_cala_y_plus")
        self.radioButton_cala_x_plus = QtWidgets.QRadioButton(self.groupBox_cala_move_dir)
        self.radioButton_cala_x_plus.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.radioButton_cala_x_plus.setObjectName("radioButton_cala_x_plus")
        self.radioButton_cala_y_minus = QtWidgets.QRadioButton(self.groupBox_cala_move_dir)
        self.radioButton_cala_y_minus.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.radioButton_cala_y_minus.setChecked(False)
        self.radioButton_cala_y_minus.setObjectName("radioButton_cala_y_minus")
        self.radioButton_cala_x_minus = QtWidgets.QRadioButton(self.groupBox_cala_move_dir)
        self.radioButton_cala_x_minus.setGeometry(QtCore.QRect(140, 20, 61, 21))
        self.radioButton_cala_x_minus.setObjectName("radioButton_cala_x_minus")
        self.pushButton_cala_move = QtWidgets.QPushButton(self.groupBox_cala_set)
        self.pushButton_cala_move.setGeometry(QtCore.QRect(10, 20, 71, 41))
        self.pushButton_cala_move.setObjectName("pushButton_cala_move")
        self.pushButton_cala_left_up = QtWidgets.QPushButton(self.groupBox_cala_set)
        self.pushButton_cala_left_up.setGeometry(QtCore.QRect(90, 20, 71, 41))
        self.pushButton_cala_left_up.setObjectName("pushButton_cala_left_up")
        self.pushButton_cala_right_bottom = QtWidgets.QPushButton(self.groupBox_cala_set)
        self.pushButton_cala_right_bottom.setGeometry(QtCore.QRect(170, 20, 71, 41))
        self.pushButton_cala_right_bottom.setObjectName("pushButton_cala_right_bottom")
        self.pushButton_cala_comp = QtWidgets.QPushButton(self.groupBox_cala_set)
        self.pushButton_cala_comp.setGeometry(QtCore.QRect(250, 20, 71, 41))
        self.pushButton_cala_comp.setObjectName("pushButton_cala_comp")
        self.pushButton_cala_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cala_start.setGeometry(QtCore.QRect(200, 200, 161, 71))
        self.pushButton_cala_start.setObjectName("pushButton_cala_start")
        self.pushButton_ctrl_null = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ctrl_null.setGeometry(QtCore.QRect(200, 110, 151, 71))
        self.pushButton_ctrl_null.setObjectName("pushButton_ctrl_null")
        cebsMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cebsMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        cebsMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cebsMainWindow)
        self.statusbar.setObjectName("statusbar")
        cebsMainWindow.setStatusBar(self.statusbar)
        self.actionSTART = QtWidgets.QAction(cebsMainWindow)
        self.actionSTART.setObjectName("actionSTART")
        self.actionSTOP = QtWidgets.QAction(cebsMainWindow)
        self.actionSTOP.setObjectName("actionSTOP")
        self.actionEXIT = QtWidgets.QAction(cebsMainWindow)
        self.actionEXIT.setObjectName("actionEXIT")
        self.actionABOUT = QtWidgets.QAction(cebsMainWindow)
        self.actionABOUT.setObjectName("actionABOUT")
        self.menu.addAction(self.actionSTART)
        self.menu.addAction(self.actionSTOP)
        self.menu_2.addAction(self.actionEXIT)
        self.menu_2.addAction(self.actionABOUT)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(cebsMainWindow)
        self.pushButton_runpg_clear.clicked.connect(cebsMainWindow.slot_runpg_clear)
        self.pushButton_runpg_test.clicked.connect(cebsMainWindow.slot_runpg_test)
        self.pushButton_ctrl_stop.clicked.connect(cebsMainWindow.slot_ctrl_stop)
        self.pushButton_ctrl_start.clicked.connect(cebsMainWindow.slot_ctrl_start)
        self.pushButton_ctrl_zero.clicked.connect(cebsMainWindow.slot_ctrl_zero)
        self.pushButton_cala_pilot.clicked.connect(cebsMainWindow.slot_cala_pilot)
        self.pushButton_ctrl_null.clicked.connect(cebsMainWindow.slot_ctrl_null)
        self.pushButton_cala_start.clicked.connect(cebsMainWindow.slot_cala_start)
        self.pushButton_cala_move.clicked.connect(cebsMainWindow.slot_cala_move)
        self.pushButton_cala_left_up.clicked.connect(cebsMainWindow.slot_cala_left_up)
        self.pushButton_cala_right_bottom.clicked.connect(cebsMainWindow.slot_cala_right_bottom)
        self.pushButton_cala_comp.clicked.connect(cebsMainWindow.slot_cala_comp)
        QtCore.QMetaObject.connectSlotsByName(cebsMainWindow)

    def retranslateUi(self, cebsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        cebsMainWindow.setWindowTitle(_translate("cebsMainWindow", "CEBS SYSTEM"))
        self.textEdit_runProgress.setHtml(_translate("cebsMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt;&gt; 2018/5/2 15:30:99 系统启动</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt;&gt; 2018/5/2 15:40:55 启动执行命令 </p></body></html>"))
        self.pushButton_ctrl_start.setText(_translate("cebsMainWindow", "启动拍照"))
        self.label_runProgress.setText(_translate("cebsMainWindow", "运行进展"))
        self.pushButton_ctrl_stop.setText(_translate("cebsMainWindow", "停止拍照"))
        self.pushButton_runpg_test.setText(_translate("cebsMainWindow", "TEST"))
        self.pushButton_runpg_clear.setText(_translate("cebsMainWindow", "清除"))
        self.pushButton_ctrl_zero.setText(_translate("cebsMainWindow", "位置归零"))
        self.pushButton_cala_pilot.setText(_translate("cebsMainWindow", "校准巡游"))
        self.groupBox_cala_set.setTitle(_translate("cebsMainWindow", "校准设定"))
        self.groupBox_cala_move_scale.setTitle(_translate("cebsMainWindow", "运动刻度"))
        self.radioButton_cala_5cm.setText(_translate("cebsMainWindow", "5cm"))
        self.radioButton_cala_05mm.setText(_translate("cebsMainWindow", "0.5mm"))
        self.radioButton_cala_1cm.setText(_translate("cebsMainWindow", "1cm"))
        self.radioButton_cala_1mm.setText(_translate("cebsMainWindow", "1mm"))
        self.radioButton_cala_5mm.setText(_translate("cebsMainWindow", "5mm"))
        self.groupBox_cala_move_dir.setTitle(_translate("cebsMainWindow", "运动方向"))
        self.radioButton_cala_y_plus.setText(_translate("cebsMainWindow", "上(Y+)"))
        self.radioButton_cala_x_plus.setText(_translate("cebsMainWindow", "右(X+)"))
        self.radioButton_cala_y_minus.setText(_translate("cebsMainWindow", "下(Y-)"))
        self.radioButton_cala_x_minus.setText(_translate("cebsMainWindow", "左(X-)"))
        self.pushButton_cala_move.setText(_translate("cebsMainWindow", "移动"))
        self.pushButton_cala_left_up.setText(_translate("cebsMainWindow", "设定左上"))
        self.pushButton_cala_right_bottom.setText(_translate("cebsMainWindow", "设定右下"))
        self.pushButton_cala_comp.setText(_translate("cebsMainWindow", "校准完成"))
        self.pushButton_cala_start.setText(_translate("cebsMainWindow", "校准启动"))
        self.pushButton_ctrl_null.setText(_translate("cebsMainWindow", "NULL"))
        self.menu.setTitle(_translate("cebsMainWindow", "控制命令"))
        self.menu_2.setTitle(_translate("cebsMainWindow", "系统设置"))
        self.actionSTART.setText(_translate("cebsMainWindow", "START"))
        self.actionSTOP.setText(_translate("cebsMainWindow", "STOP"))
        self.actionEXIT.setText(_translate("cebsMainWindow", "EXIT"))
        self.actionABOUT.setText(_translate("cebsMainWindow", "ABOUT"))

