# Generated by Django 2.1 on 2018-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbComm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=32, verbose_name='用户')),
                ('userPwd', models.CharField(max_length=32, verbose_name='密码')),
                ('nickName', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('homeAddress', models.CharField(max_length=50, null=True)),
                ('homeCity', models.CharField(max_length=60, null=True)),
                ('stateProvince', models.CharField(max_length=30, null=True)),
                ('homeCountry', models.CharField(max_length=50, null=True)),
                ('website', models.URLField(null=True)),
                ('emailaddr', models.EmailField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ipaddr', models.GenericIPAddressField(null=True)),
            ],
        ),
    ]
