# Generated by Django 2.1 on 2018-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbComm', '0002_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(max_length=32),
        ),
    ]
