# Generated by Django 2.1.7 on 2019-02-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f12iwdp_company_jsapi_ticket',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('cordid', models.CharField(max_length=50)),
                ('jsticket', models.TextField()),
                ('last_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f12iwdp_integral_setting',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('accept', models.IntegerField(default=0)),
                ('refuse', models.IntegerField(default=0)),
                ('finish', models.IntegerField(default=0)),
                ('unfinish', models.IntegerField(default=0)),
                ('outtime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f12iwdp_task',
            fields=[
                ('taskid', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=25)),
                ('taskdescribe', models.TextField(null=True)),
                ('tasklevel', models.IntegerField(default=0)),
                ('taskstart', models.DateTimeField()),
                ('taskend', models.DateTimeField()),
                ('taskremind', models.DateTimeField(null=True)),
                ('taskendtime', models.DateTimeField(null=True)),
                ('taskenclosure', models.TextField(null=True)),
                ('tasksoundid', models.CharField(max_length=30, null=True)),
                ('taskstate', models.IntegerField(default=0)),
                ('taskreview', models.IntegerField(default=0)),
                ('comment', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f12iwdp_user',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=14)),
                ('uemail', models.CharField(max_length=40, null=True)),
                ('uavatar', models.TextField(null=True)),
                ('utelephone', models.CharField(max_length=15, null=True)),
                ('ucompanyid', models.CharField(max_length=50, null=True)),
                ('ucompanyname', models.CharField(max_length=50, null=True)),
                ('udepartmentid', models.CharField(max_length=50, null=True)),
                ('udepartmentname', models.CharField(max_length=50, null=True)),
                ('ulevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f12iwdp_user_task',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(db_index=True, default=0)),
                ('taskaccept', models.IntegerField(default=0)),
                ('integral', models.IntegerField(default=0)),
                ('show', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF12iwdp.dct_t_l3f12iwdp_task')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF12iwdp.dct_t_l3f12iwdp_user')),
            ],
        ),
        migrations.AddField(
            model_name='dct_t_l3f12iwdp_integral_setting',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF12iwdp.dct_t_l3f12iwdp_user'),
        ),
    ]
