# Generated by Django 2.0.2 on 2019-06-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_cebs_batch_info',
            fields=[
                ('snbatch', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('comp_nbr', models.IntegerField(default=4)),
                ('usr_def1', models.CharField(max_length=256)),
                ('usr_def2', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_cali_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platetype', models.CharField(max_length=50)),
                ('calitime', models.DateTimeField(auto_now=True)),
                ('left_bot_x', models.IntegerField(default=0)),
                ('left_bot_y', models.IntegerField(default=0)),
                ('right_up_x', models.IntegerField(default=0)),
                ('right_up_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_config_eleg',
            fields=[
                ('confid', models.AutoField(primary_key=True, serialize=False)),
                ('fixpoint', models.BooleanField(default=False)),
                ('autovideo', models.BooleanField(default=False)),
                ('autodist', models.BooleanField(default=False)),
                ('addset', models.BooleanField(default=True)),
                ('autocap', models.BooleanField(default=False)),
                ('autoperiod', models.IntegerField(default=60)),
                ('videotime', models.IntegerField(default=3)),
                ('slimit', models.IntegerField(default=200)),
                ('smlimit', models.IntegerField(default=500)),
                ('mblimit', models.IntegerField(default=2000)),
                ('blimit', models.IntegerField(default=5000)),
                ('accspeed', models.IntegerField(default=4)),
                ('decspeed', models.IntegerField(default=4)),
                ('movespeed', models.IntegerField(default=4)),
                ('zero_spd', models.IntegerField(default=4)),
                ('zero_dec', models.IntegerField(default=4)),
                ('back_step', models.IntegerField(default=4)),
                ('autoclfy', models.BooleanField(default=False)),
                ('autowork', models.BooleanField(default=False)),
                ('blurylimit', models.IntegerField(default=300)),
                ('zero_acc', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_config_stackcell',
            fields=[
                ('confid', models.AutoField(primary_key=True, serialize=False)),
                ('addset', models.BooleanField(default=True)),
                ('line_area', models.IntegerField(default=10000)),
                ('line_width', models.IntegerField(default=44)),
                ('line_long', models.IntegerField(default=222)),
                ('line_dilate', models.IntegerField(default=22)),
                ('area_up', models.IntegerField(default=1000000)),
                ('area_low', models.IntegerField(default=100000)),
                ('area_dilate', models.IntegerField(default=1500)),
                ('area_erode', models.IntegerField(default=5)),
                ('square_min', models.IntegerField(default=920)),
                ('square_max', models.IntegerField(default=1500)),
                ('radius_min', models.IntegerField(default=19)),
                ('radius_max', models.IntegerField(default=23)),
                ('cell_dilate', models.IntegerField(default=61)),
                ('cell_erode', models.IntegerField(default=5)),
                ('cell_round', models.IntegerField(default=50)),
                ('cell_distance', models.IntegerField(default=30)),
                ('train_delay', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_language_config',
            fields=[
                ('lang_abbr', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=20)),
                ('lang_icon', models.CharField(max_length=20)),
                ('defaultflag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_language_dict',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=200)),
                ('chinese', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_object_profile',
            fields=[
                ('objid', models.AutoField(primary_key=True, serialize=False)),
                ('defaultflag', models.BooleanField(default=False)),
                ('objname', models.CharField(db_index=True, max_length=20)),
                ('objtype', models.IntegerField(default=1)),
                ('dir_origin', models.CharField(max_length=100)),
                ('dir_middle', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_platform_info',
            fields=[
                ('platoption', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_product_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_code', models.CharField(max_length=20)),
                ('hw_ver', models.IntegerField(blank=True, null=True)),
                ('sw_ver', models.IntegerField(blank=True, null=True)),
                ('authtoken', models.CharField(max_length=128)),
                ('mfd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_pvci_eleg',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('snbatch', models.IntegerField(default=0)),
                ('snhole', models.IntegerField(default=0)),
                ('file_attr', models.CharField(max_length=50)),
                ('name_before', models.CharField(max_length=20)),
                ('video_before', models.CharField(max_length=100)),
                ('cap_time', models.DateTimeField(auto_now_add=True)),
                ('name_after', models.CharField(max_length=20)),
                ('rec_time', models.DateTimeField(auto_now=True)),
                ('bigalive', models.IntegerField(default=0)),
                ('bigdead', models.IntegerField(default=0)),
                ('midalive', models.IntegerField(default=0)),
                ('middead', models.IntegerField(default=0)),
                ('smaalive', models.IntegerField(default=0)),
                ('smdead', models.IntegerField(default=0)),
                ('totalalive', models.IntegerField(default=0)),
                ('totaldead', models.IntegerField(default=0)),
                ('totalsum', models.IntegerField(default=0)),
                ('doneflag', models.BooleanField(default=False)),
                ('memo', models.CharField(max_length=500)),
                ('confid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_object_profile')),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_result_eleg',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('snbatch', models.IntegerField(default=0)),
                ('snhole', models.IntegerField(default=0)),
                ('file_attr', models.IntegerField(db_index=True, default=1)),
                ('name_before', models.CharField(max_length=20)),
                ('cap_time', models.DateTimeField(auto_now_add=True)),
                ('name_after', models.CharField(max_length=20)),
                ('rec_time', models.DateTimeField(auto_now=True)),
                ('bigalive', models.IntegerField(default=0)),
                ('bigdead', models.IntegerField(default=0)),
                ('midalive', models.IntegerField(default=0)),
                ('middead', models.IntegerField(default=0)),
                ('smaalive', models.IntegerField(default=0)),
                ('smdead', models.IntegerField(default=0)),
                ('totalalive', models.IntegerField(default=0)),
                ('totaldead', models.IntegerField(default=0)),
                ('totalsum', models.IntegerField(default=0)),
                ('doneflag', models.BooleanField(default=False)),
                ('memo', models.CharField(max_length=500)),
                ('confid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_object_profile')),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_result_stackcell',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('file_attr', models.IntegerField(default=1)),
                ('name_before', models.CharField(max_length=20)),
                ('name_after', models.CharField(max_length=20)),
                ('rec_time', models.DateTimeField(auto_now=True)),
                ('totalnbr', models.IntegerField(default=0)),
                ('validnbr', models.IntegerField(default=0)),
                ('doneflag', models.BooleanField(default=False)),
                ('memo', models.CharField(max_length=500)),
                ('confid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_object_profile')),
            ],
        ),
        migrations.CreateModel(
            name='t_cebs_user_sheet',
            fields=[
                ('uid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=20)),
                ('pass_word', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField(default=4, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('memo', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_lcebs_user_right_action',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet')),
            ],
        ),
        migrations.CreateModel(
            name='t_lcebs_user_right_menu',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet')),
            ],
        ),
        migrations.AddField(
            model_name='t_cebs_object_profile',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet'),
        ),
        migrations.AddField(
            model_name='t_cebs_config_stackcell',
            name='objid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_object_profile'),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='objid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_object_profile'),
        ),
        migrations.AddField(
            model_name='t_cebs_cali_profile',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet'),
        ),
        migrations.AddField(
            model_name='t_cebs_batch_info',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet'),
        ),
    ]
