# Generated by Django 2.1 on 2018-02-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyExecLog',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('timeStampExec', models.DateTimeField(auto_now=True, null=True)),
                ('pageLen', models.IntegerField(default=0)),
                ('pageWidth', models.IntegerField(default=0)),
                ('resTotal', models.IntegerField(default=0)),
                ('resTotalAlive', models.IntegerField(default=0)),
                ('resTotalDead', models.IntegerField(default=0)),
                ('resSmallAlive', models.IntegerField(default=0)),
                ('resSmallDead', models.IntegerField(default=0)),
                ('resMidAlive', models.IntegerField(default=0)),
                ('resMidDead', models.IntegerField(default=0)),
                ('resBigAlive', models.IntegerField(default=0)),
                ('resBigDead', models.IntegerField(default=0)),
                ('resUnclassifyAlive', models.IntegerField(default=0)),
                ('resUnclassifyDead', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubmitMission',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('timeStampSubmit', models.DateTimeField(auto_now=True, null=True)),
                ('pageNbr', models.IntegerField(default=0)),
                ('filePath', models.CharField(max_length=254)),
                ('fileName', models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
