# Generated by Django 2.1 on 2018-02-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0002_auto_20180220_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerSubmitMission',
            new_name='CustomerMission',
        ),
    ]
