# Generated by Django 2.1.7 on 2019-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0003_auto_20190228_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='platetype',
        ),
        migrations.AddField(
            model_name='t_cebs_cali_profile',
            name='dir_originplatetype',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='t_cebs_product_profile',
            name='mfd',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='t_cebs_result_eleg',
            name='cap_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='t_cebs_result_eleg',
            name='rec_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='t_cebs_user_sheet',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
