# Generated by Django 2.1.7 on 2019-03-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0004_auto_20190301_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_cebs_cali_profile',
            old_name='dir_originplatetype',
            new_name='platetype',
        ),
    ]
