# Generated by Django 2.0.2 on 2019-04-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0009_auto_20190302_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_cebs_batch_info',
            fields=[
                ('snbatch', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('comp_nbr', models.IntegerField(default=4)),
                ('usr_def1', models.CharField(max_length=256)),
                ('usr_def2', models.CharField(max_length=256)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbCebs.t_cebs_user_sheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='accspeed',
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='back_step',
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='decspeed',
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='movespeed',
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='zero_dec',
        ),
        migrations.RemoveField(
            model_name='t_cebs_cali_profile',
            name='zero_spd',
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='accspeed',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='back_step',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='decspeed',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='movespeed',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='zero_dec',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_config_eleg',
            name='zero_spd',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='t_cebs_object_profile',
            name='defaultflag',
            field=models.BooleanField(default=False),
        ),
    ]
