# Generated by Django 2.0.2 on 2019-04-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbCebs', '0010_auto_20190411_1937'),
        ('DappDbCebs', '0010_auto_20190412_1010'),
    ]

    operations = [
    ]
