# Generated by Django 2.1a1 on 2018-08-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DappDbF2cm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f6pm_perfdata',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('restartcnt', models.IntegerField(default=0)),
                ('networkconncnt', models.IntegerField(default=0)),
                ('networkconnfailcnt', models.IntegerField(default=0)),
                ('networkdisccnt', models.IntegerField(default=0)),
                ('socketdisccnt', models.IntegerField(default=0)),
                ('cpuoccupy', models.IntegerField(default=0)),
                ('memoccupy', models.IntegerField(default=0)),
                ('diskoccupy', models.IntegerField(default=0)),
                ('cputemp', models.IntegerField(default=0)),
                ('dev_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_device_common')),
                ('site_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_site_common')),
            ],
        ),
    ]
