# Generated by Django 2.1a1 on 2018-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF6pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f6pm_perfdata',
            name='alarmcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dct_t_l3f6pm_perfdata',
            name='dischomecnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dct_t_l3f6pm_perfdata',
            name='vmerrcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dct_t_l3f6pm_perfdata',
            name='workcontmins',
            field=models.IntegerField(default=0),
        ),
    ]
