# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fmpt2mainform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ObjFmpt2MainForm(object):
    def setupUi(self, ObjFmpt2MainForm):
        ObjFmpt2MainForm.setObjectName("ObjFmpt2MainForm")
        ObjFmpt2MainForm.resize(1420, 748)
        ObjFmpt2MainForm.setMinimumSize(QtCore.QSize(1420, 700))
        ObjFmpt2MainForm.setMouseTracking(True)
        ObjFmpt2MainForm.setTabletTracking(True)
        ObjFmpt2MainForm.setAcceptDrops(True)
        ObjFmpt2MainForm.setAutoFillBackground(False)
        ObjFmpt2MainForm.setDocumentMode(False)
        ObjFmpt2MainForm.setDockNestingEnabled(True)
        ObjFmpt2MainForm.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(ObjFmpt2MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_oli_OperationLogInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_oli_OperationLogInfo.setGeometry(QtCore.QRect(1160, 10, 251, 651))
        self.groupBox_oli_OperationLogInfo.setObjectName("groupBox_oli_OperationLogInfo")
        self.textEdit_OprLogInfo = QtWidgets.QTextEdit(self.groupBox_oli_OperationLogInfo)
        self.textEdit_OprLogInfo.setGeometry(QtCore.QRect(10, 20, 231, 591))
        self.textEdit_OprLogInfo.setMouseTracking(True)
        self.textEdit_OprLogInfo.setTabletTracking(True)
        self.textEdit_OprLogInfo.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textEdit_OprLogInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_OprLogInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_OprLogInfo.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_OprLogInfo.setTabChangesFocus(True)
        self.textEdit_OprLogInfo.setReadOnly(False)
        self.textEdit_OprLogInfo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_OprLogInfo.setObjectName("textEdit_OprLogInfo")
        self.pushButton_oli_clear = QtWidgets.QPushButton(self.groupBox_oli_OperationLogInfo)
        self.pushButton_oli_clear.setGeometry(QtCore.QRect(130, 620, 71, 21))
        self.pushButton_oli_clear.setObjectName("pushButton_oli_clear")
        self.pushButton_oli_test = QtWidgets.QPushButton(self.groupBox_oli_OperationLogInfo)
        self.pushButton_oli_test.setGeometry(QtCore.QRect(40, 620, 71, 21))
        self.pushButton_oli_test.setObjectName("pushButton_oli_test")
        self.groupBox_keo_KeyElementOperation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_keo_KeyElementOperation.setGeometry(QtCore.QRect(10, 160, 561, 411))
        self.groupBox_keo_KeyElementOperation.setObjectName("groupBox_keo_KeyElementOperation")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_keo_KeyElementOperation)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 46, 381, 275))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_keo_hwType = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_hwType.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_hwType.setObjectName("label_keo_hwType")
        self.horizontalLayout_19.addWidget(self.label_keo_hwType)
        self.pushButton_keo_hwType_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_hwType_read.setObjectName("pushButton_keo_hwType_read")
        self.horizontalLayout_19.addWidget(self.pushButton_keo_hwType_read)
        self.pushButton_keo_hwType_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_hwType_write.setObjectName("pushButton_keo_hwType_write")
        self.horizontalLayout_19.addWidget(self.pushButton_keo_hwType_write)
        self.lineEdit_keo_hwType = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_hwType.setObjectName("lineEdit_keo_hwType")
        self.horizontalLayout_19.addWidget(self.lineEdit_keo_hwType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_keo_hwPemId = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_hwPemId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_hwPemId.setObjectName("label_keo_hwPemId")
        self.horizontalLayout_20.addWidget(self.label_keo_hwPemId)
        self.pushButton_keo_hwPemId_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_hwPemId_read.setObjectName("pushButton_keo_hwPemId_read")
        self.horizontalLayout_20.addWidget(self.pushButton_keo_hwPemId_read)
        self.pushButton_keo_hwPemId_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_hwPemId_write.setObjectName("pushButton_keo_hwPemId_write")
        self.horizontalLayout_20.addWidget(self.pushButton_keo_hwPemId_write)
        self.lineEdit_keo_hwPemId = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_hwPemId.setObjectName("lineEdit_keo_hwPemId")
        self.horizontalLayout_20.addWidget(self.lineEdit_keo_hwPemId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_keo_swRelId = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_swRelId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_swRelId.setObjectName("label_keo_swRelId")
        self.horizontalLayout_21.addWidget(self.label_keo_swRelId)
        self.pushButton_keo_swRelId_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swRelId_read.setObjectName("pushButton_keo_swRelId_read")
        self.horizontalLayout_21.addWidget(self.pushButton_keo_swRelId_read)
        self.pushButton_keo_swRelId_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swRelId_write.setObjectName("pushButton_keo_swRelId_write")
        self.horizontalLayout_21.addWidget(self.pushButton_keo_swRelId_write)
        self.lineEdit_keo_swRelId = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_swRelId.setObjectName("lineEdit_keo_swRelId")
        self.horizontalLayout_21.addWidget(self.lineEdit_keo_swRelId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_keo_swVerId = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_swVerId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_swVerId.setObjectName("label_keo_swVerId")
        self.horizontalLayout_22.addWidget(self.label_keo_swVerId)
        self.pushButton_keo_swVerId_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swVerId_read.setObjectName("pushButton_keo_swVerId_read")
        self.horizontalLayout_22.addWidget(self.pushButton_keo_swVerId_read)
        self.pushButton_keo_swVerId_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swVerId_write.setObjectName("pushButton_keo_swVerId_write")
        self.horizontalLayout_22.addWidget(self.pushButton_keo_swVerId_write)
        self.lineEdit_keo_swVerId = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_swVerId.setObjectName("lineEdit_keo_swVerId")
        self.horizontalLayout_22.addWidget(self.lineEdit_keo_swVerId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_keo_swUpgradeFlag = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_swUpgradeFlag.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_swUpgradeFlag.setObjectName("label_keo_swUpgradeFlag")
        self.horizontalLayout_23.addWidget(self.label_keo_swUpgradeFlag)
        self.pushButton_keo_swUpgradeFlag_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swUpgradeFlag_read.setObjectName("pushButton_keo_swUpgradeFlag_read")
        self.horizontalLayout_23.addWidget(self.pushButton_keo_swUpgradeFlag_read)
        self.pushButton_keo_swUpgradeFlag_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swUpgradeFlag_write.setObjectName("pushButton_keo_swUpgradeFlag_write")
        self.horizontalLayout_23.addWidget(self.pushButton_keo_swUpgradeFlag_write)
        self.lineEdit_keo_swUpgradeFlag = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_swUpgradeFlag.setObjectName("lineEdit_keo_swUpgradeFlag")
        self.horizontalLayout_23.addWidget(self.lineEdit_keo_swUpgradeFlag)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_keo_swUpgPollId = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_swUpgPollId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_swUpgPollId.setObjectName("label_keo_swUpgPollId")
        self.horizontalLayout_24.addWidget(self.label_keo_swUpgPollId)
        self.pushButton_keo_swUpgPollId_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swUpgPollId_read.setObjectName("pushButton_keo_swUpgPollId_read")
        self.horizontalLayout_24.addWidget(self.pushButton_keo_swUpgPollId_read)
        self.pushButton_keo_swUpgPollId_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_swUpgPollId_write.setObjectName("pushButton_keo_swUpgPollId_write")
        self.horizontalLayout_24.addWidget(self.pushButton_keo_swUpgPollId_write)
        self.lineEdit_keo_swUpgPollId = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_swUpgPollId.setObjectName("lineEdit_keo_swUpgPollId")
        self.horizontalLayout_24.addWidget(self.lineEdit_keo_swUpgPollId)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_keo_bootIndex = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_bootIndex.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_bootIndex.setObjectName("label_keo_bootIndex")
        self.horizontalLayout_25.addWidget(self.label_keo_bootIndex)
        self.pushButton_keo_bootIndex_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_bootIndex_read.setObjectName("pushButton_keo_bootIndex_read")
        self.horizontalLayout_25.addWidget(self.pushButton_keo_bootIndex_read)
        self.pushButton_keo_bootInde_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_bootInde_write.setObjectName("pushButton_keo_bootInde_write")
        self.horizontalLayout_25.addWidget(self.pushButton_keo_bootInde_write)
        self.lineEdit_keo_bootIndex = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_bootIndex.setObjectName("lineEdit_keo_bootIndex")
        self.horizontalLayout_25.addWidget(self.lineEdit_keo_bootIndex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_keo_bootAreaMax = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_bootAreaMax.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_bootAreaMax.setObjectName("label_keo_bootAreaMax")
        self.horizontalLayout_26.addWidget(self.label_keo_bootAreaMax)
        self.pushButton_keo_bootAreaMax_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_bootAreaMax_read.setObjectName("pushButton_keo_bootAreaMax_read")
        self.horizontalLayout_26.addWidget(self.pushButton_keo_bootAreaMax_read)
        self.pushButton_keo_bootAreaMax_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_bootAreaMax_write.setObjectName("pushButton_keo_bootAreaMax_write")
        self.horizontalLayout_26.addWidget(self.pushButton_keo_bootAreaMax_write)
        self.lineEdit_keo_bootAreaMax = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_bootAreaMax.setObjectName("lineEdit_keo_bootAreaMax")
        self.horizontalLayout_26.addWidget(self.lineEdit_keo_bootAreaMax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_keo_cypherKey = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_keo_cypherKey.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_cypherKey.setObjectName("label_keo_cypherKey")
        self.horizontalLayout_27.addWidget(self.label_keo_cypherKey)
        self.pushButton_keo_cypherKey_read = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_cypherKey_read.setObjectName("pushButton_keo_cypherKey_read")
        self.horizontalLayout_27.addWidget(self.pushButton_keo_cypherKey_read)
        self.pushButton_keo_cypherKey_write = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_keo_cypherKey_write.setObjectName("pushButton_keo_cypherKey_write")
        self.horizontalLayout_27.addWidget(self.pushButton_keo_cypherKey_write)
        self.lineEdit_keo_cypherKey = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_keo_cypherKey.setObjectName("lineEdit_keo_cypherKey")
        self.horizontalLayout_27.addWidget(self.lineEdit_keo_cypherKey)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.groupBox_keo_LoadBootcfg = QtWidgets.QGroupBox(self.groupBox_keo_KeyElementOperation)
        self.groupBox_keo_LoadBootcfg.setGeometry(QtCore.QRect(400, 20, 161, 301))
        self.groupBox_keo_LoadBootcfg.setObjectName("groupBox_keo_LoadBootcfg")
        self.label_keo_cfgFile = QtWidgets.QLabel(self.groupBox_keo_LoadBootcfg)
        self.label_keo_cfgFile.setGeometry(QtCore.QRect(10, 34, 54, 12))
        self.label_keo_cfgFile.setObjectName("label_keo_cfgFile")
        self.pushButton_keo_cfgFile_Browse = QtWidgets.QPushButton(self.groupBox_keo_LoadBootcfg)
        self.pushButton_keo_cfgFile_Browse.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.pushButton_keo_cfgFile_Browse.setObjectName("pushButton_keo_cfgFile_Browse")
        self.lineEdit_keo_cfgFile = QtWidgets.QLineEdit(self.groupBox_keo_LoadBootcfg)
        self.lineEdit_keo_cfgFile.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.lineEdit_keo_cfgFile.setObjectName("lineEdit_keo_cfgFile")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_keo_LoadBootcfg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 130, 142, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_keo_cfgFile_LoadFile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_keo_cfgFile_LoadFile.setObjectName("pushButton_keo_cfgFile_LoadFile")
        self.verticalLayout.addWidget(self.pushButton_keo_cfgFile_LoadFile)
        self.pushButton_keo_cfgFile_SaveFile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_keo_cfgFile_SaveFile.setObjectName("pushButton_keo_cfgFile_SaveFile")
        self.verticalLayout.addWidget(self.pushButton_keo_cfgFile_SaveFile)
        self.pushButton_keo_cfgFile_ReadAllFromHw = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_keo_cfgFile_ReadAllFromHw.setObjectName("pushButton_keo_cfgFile_ReadAllFromHw")
        self.verticalLayout.addWidget(self.pushButton_keo_cfgFile_ReadAllFromHw)
        self.pushButton_keo_cfgFile_WriteAllToHw = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_keo_cfgFile_WriteAllToHw.setObjectName("pushButton_keo_cfgFile_WriteAllToHw")
        self.verticalLayout.addWidget(self.pushButton_keo_cfgFile_WriteAllToHw)
        self.groupBox_keo_SingleByteOpr = QtWidgets.QGroupBox(self.groupBox_keo_KeyElementOperation)
        self.groupBox_keo_SingleByteOpr.setGeometry(QtCore.QRect(10, 330, 541, 71))
        self.groupBox_keo_SingleByteOpr.setObjectName("groupBox_keo_SingleByteOpr")
        self.label_keo_byteopr_address = QtWidgets.QLabel(self.groupBox_keo_SingleByteOpr)
        self.label_keo_byteopr_address.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_keo_byteopr_address.setObjectName("label_keo_byteopr_address")
        self.lineEdit_keo_byteopr_address = QtWidgets.QLineEdit(self.groupBox_keo_SingleByteOpr)
        self.lineEdit_keo_byteopr_address.setGeometry(QtCore.QRect(60, 20, 81, 18))
        self.lineEdit_keo_byteopr_address.setObjectName("lineEdit_keo_byteopr_address")
        self.radioButton_keo_byteopr_byte = QtWidgets.QRadioButton(self.groupBox_keo_SingleByteOpr)
        self.radioButton_keo_byteopr_byte.setGeometry(QtCore.QRect(180, 20, 81, 16))
        self.radioButton_keo_byteopr_byte.setObjectName("radioButton_keo_byteopr_byte")
        self.radioButton_keo_byteopr_short = QtWidgets.QRadioButton(self.groupBox_keo_SingleByteOpr)
        self.radioButton_keo_byteopr_short.setGeometry(QtCore.QRect(280, 20, 81, 16))
        self.radioButton_keo_byteopr_short.setChecked(True)
        self.radioButton_keo_byteopr_short.setObjectName("radioButton_keo_byteopr_short")
        self.radioButton_keo_byteopr_int = QtWidgets.QRadioButton(self.groupBox_keo_SingleByteOpr)
        self.radioButton_keo_byteopr_int.setGeometry(QtCore.QRect(370, 20, 81, 16))
        self.radioButton_keo_byteopr_int.setObjectName("radioButton_keo_byteopr_int")
        self.pushButton_keo_byteopr_read = QtWidgets.QPushButton(self.groupBox_keo_SingleByteOpr)
        self.pushButton_keo_byteopr_read.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_keo_byteopr_read.setObjectName("pushButton_keo_byteopr_read")
        self.pushButton_keo_byteopr_write = QtWidgets.QPushButton(self.groupBox_keo_SingleByteOpr)
        self.pushButton_keo_byteopr_write.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.pushButton_keo_byteopr_write.setObjectName("pushButton_keo_byteopr_write")
        self.lineEdit_keo_byteopr_result = QtWidgets.QLineEdit(self.groupBox_keo_SingleByteOpr)
        self.lineEdit_keo_byteopr_result.setGeometry(QtCore.QRect(190, 40, 341, 18))
        self.lineEdit_keo_byteopr_result.setObjectName("lineEdit_keo_byteopr_result")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_keo_KeyElementOperation)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 381, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_keo_equLable = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_keo_equLable.setMinimumSize(QtCore.QSize(91, 0))
        self.label_keo_equLable.setObjectName("label_keo_equLable")
        self.horizontalLayout_28.addWidget(self.label_keo_equLable)
        self.pushButton_keo_equLable_read = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_keo_equLable_read.setObjectName("pushButton_keo_equLable_read")
        self.horizontalLayout_28.addWidget(self.pushButton_keo_equLable_read)
        self.pushButton_keo_equLable_write = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_keo_equLable_write.setObjectName("pushButton_keo_equLable_write")
        self.horizontalLayout_28.addWidget(self.pushButton_keo_equLable_write)
        self.lineEdit_keo_equLable = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_keo_equLable.setObjectName("lineEdit_keo_equLable")
        self.horizontalLayout_28.addWidget(self.lineEdit_keo_equLable)
        self.groupBox_fio_FullImageOperation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_fio_FullImageOperation.setGeometry(QtCore.QRect(10, 580, 561, 81))
        self.groupBox_fio_FullImageOperation.setObjectName("groupBox_fio_FullImageOperation")
        self.pushButton_fio_file_browse = QtWidgets.QPushButton(self.groupBox_fio_FullImageOperation)
        self.pushButton_fio_file_browse.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.pushButton_fio_file_browse.setObjectName("pushButton_fio_file_browse")
        self.lineEdit_fio_file_dir = QtWidgets.QLineEdit(self.groupBox_fio_FullImageOperation)
        self.lineEdit_fio_file_dir.setGeometry(QtCore.QRect(10, 50, 541, 20))
        self.lineEdit_fio_file_dir.setObjectName("lineEdit_fio_file_dir")
        self.pushButton_fio_file_save = QtWidgets.QPushButton(self.groupBox_fio_FullImageOperation)
        self.pushButton_fio_file_save.setGeometry(QtCore.QRect(80, 20, 231, 23))
        self.pushButton_fio_file_save.setObjectName("pushButton_fio_file_save")
        self.pushButton_fio_file_load = QtWidgets.QPushButton(self.groupBox_fio_FullImageOperation)
        self.pushButton_fio_file_load.setGeometry(QtCore.QRect(320, 20, 231, 23))
        self.pushButton_fio_file_load.setObjectName("pushButton_fio_file_load")
        self.groupBox_aim_firmwareDown = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_aim_firmwareDown.setGeometry(QtCore.QRect(580, 140, 571, 471))
        self.groupBox_aim_firmwareDown.setObjectName("groupBox_aim_firmwareDown")
        self.groupBox_aim_fac = QtWidgets.QGroupBox(self.groupBox_aim_firmwareDown)
        self.groupBox_aim_fac.setGeometry(QtCore.QRect(10, 20, 551, 141))
        self.groupBox_aim_fac.setObjectName("groupBox_aim_fac")
        self.label_aim_fac_addr = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_addr.setGeometry(QtCore.QRect(10, 24, 54, 12))
        self.label_aim_fac_addr.setObjectName("label_aim_fac_addr")
        self.pushButton_aim_fac_addr_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_addr_read.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.pushButton_aim_fac_addr_read.setObjectName("pushButton_aim_fac_addr_read")
        self.lineEdit_aim_fac_addr_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_addr_text.setGeometry(QtCore.QRect(160, 20, 101, 20))
        self.lineEdit_aim_fac_addr_text.setObjectName("lineEdit_aim_fac_addr_text")
        self.label_aim_fac_swRel = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_swRel.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_aim_fac_swRel.setObjectName("label_aim_fac_swRel")
        self.label_aim_fac_valid = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_valid.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_aim_fac_valid.setObjectName("label_aim_fac_valid")
        self.pushButton_aim_fac_swRel_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_swRel_read.setGeometry(QtCore.QRect(70, 50, 31, 21))
        self.pushButton_aim_fac_swRel_read.setObjectName("pushButton_aim_fac_swRel_read")
        self.pushButton_aim_fac_swRel_set = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_swRel_set.setGeometry(QtCore.QRect(110, 50, 31, 21))
        self.pushButton_aim_fac_swRel_set.setObjectName("pushButton_aim_fac_swRel_set")
        self.pushButton_aim_fac_valid_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_valid_read.setGeometry(QtCore.QRect(70, 80, 71, 21))
        self.pushButton_aim_fac_valid_read.setObjectName("pushButton_aim_fac_valid_read")
        self.lineEdit_aim_fac_swRel_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_swRel_text.setGeometry(QtCore.QRect(160, 50, 101, 20))
        self.lineEdit_aim_fac_swRel_text.setObjectName("lineEdit_aim_fac_swRel_text")
        self.lineEdit_aim_fac_valid_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_valid_text.setGeometry(QtCore.QRect(160, 80, 101, 20))
        self.lineEdit_aim_fac_valid_text.setObjectName("lineEdit_aim_fac_valid_text")
        self.lineEdit_aim_fac_len_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_len_text.setGeometry(QtCore.QRect(430, 80, 101, 20))
        self.lineEdit_aim_fac_len_text.setObjectName("lineEdit_aim_fac_len_text")
        self.lineEdit_aim_fac_chk_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_chk_text.setGeometry(QtCore.QRect(430, 20, 101, 20))
        self.lineEdit_aim_fac_chk_text.setObjectName("lineEdit_aim_fac_chk_text")
        self.label_aim_fac_len = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_len.setGeometry(QtCore.QRect(280, 80, 54, 12))
        self.label_aim_fac_len.setObjectName("label_aim_fac_len")
        self.pushButton_aim_fac_chk_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_chk_read.setGeometry(QtCore.QRect(340, 20, 31, 21))
        self.pushButton_aim_fac_chk_read.setObjectName("pushButton_aim_fac_chk_read")
        self.lineEdit_aim_fac_swVer_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_swVer_text.setGeometry(QtCore.QRect(430, 50, 101, 20))
        self.lineEdit_aim_fac_swVer_text.setObjectName("lineEdit_aim_fac_swVer_text")
        self.pushButton_aim_fac_swVer_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_swVer_read.setGeometry(QtCore.QRect(340, 50, 31, 21))
        self.pushButton_aim_fac_swVer_read.setObjectName("pushButton_aim_fac_swVer_read")
        self.pushButton_aim_fac_swVer_set = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_swVer_set.setGeometry(QtCore.QRect(380, 50, 31, 21))
        self.pushButton_aim_fac_swVer_set.setObjectName("pushButton_aim_fac_swVer_set")
        self.pushButton_aim_fac_len_read = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_len_read.setGeometry(QtCore.QRect(340, 80, 71, 21))
        self.pushButton_aim_fac_len_read.setObjectName("pushButton_aim_fac_len_read")
        self.label_aim_fac_swVer = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_swVer.setGeometry(QtCore.QRect(280, 50, 54, 12))
        self.label_aim_fac_swVer.setObjectName("label_aim_fac_swVer")
        self.label_aim_fac_chk = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_chk.setGeometry(QtCore.QRect(280, 24, 54, 12))
        self.label_aim_fac_chk.setObjectName("label_aim_fac_chk")
        self.pushButton_aim_fac_chk_chk = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_chk_chk.setGeometry(QtCore.QRect(380, 20, 31, 21))
        self.pushButton_aim_fac_chk_chk.setObjectName("pushButton_aim_fac_chk_chk")
        self.label_aim_fac_file = QtWidgets.QLabel(self.groupBox_aim_fac)
        self.label_aim_fac_file.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_aim_fac_file.setObjectName("label_aim_fac_file")
        self.lineEdit_aim_fac_file_text = QtWidgets.QLineEdit(self.groupBox_aim_fac)
        self.lineEdit_aim_fac_file_text.setGeometry(QtCore.QRect(70, 110, 261, 20))
        self.lineEdit_aim_fac_file_text.setObjectName("lineEdit_aim_fac_file_text")
        self.pushButton_aim_fac_file_browse = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_file_browse.setGeometry(QtCore.QRect(350, 110, 71, 21))
        self.pushButton_aim_fac_file_browse.setObjectName("pushButton_aim_fac_file_browse")
        self.pushButton_aim_fac_file_update = QtWidgets.QPushButton(self.groupBox_aim_fac)
        self.pushButton_aim_fac_file_update.setGeometry(QtCore.QRect(450, 110, 71, 21))
        self.pushButton_aim_fac_file_update.setObjectName("pushButton_aim_fac_file_update")
        self.groupBox_aim_app2 = QtWidgets.QGroupBox(self.groupBox_aim_firmwareDown)
        self.groupBox_aim_app2.setGeometry(QtCore.QRect(10, 320, 551, 141))
        self.groupBox_aim_app2.setObjectName("groupBox_aim_app2")
        self.label_aim_app2_addr = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_addr.setGeometry(QtCore.QRect(10, 24, 54, 12))
        self.label_aim_app2_addr.setObjectName("label_aim_app2_addr")
        self.pushButton_aim_app2_addr_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_addr_read.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.pushButton_aim_app2_addr_read.setObjectName("pushButton_aim_app2_addr_read")
        self.lineEdit_aim_app2_addr_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_addr_text.setGeometry(QtCore.QRect(160, 20, 101, 20))
        self.lineEdit_aim_app2_addr_text.setObjectName("lineEdit_aim_app2_addr_text")
        self.label_aim_app2_swRel = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_swRel.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_aim_app2_swRel.setObjectName("label_aim_app2_swRel")
        self.label_aim_app2_valid = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_valid.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_aim_app2_valid.setObjectName("label_aim_app2_valid")
        self.pushButton_aim_app2_swRel_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_swRel_read.setGeometry(QtCore.QRect(70, 50, 31, 21))
        self.pushButton_aim_app2_swRel_read.setObjectName("pushButton_aim_app2_swRel_read")
        self.pushButton_aim_app2_swRel_set = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_swRel_set.setGeometry(QtCore.QRect(110, 50, 31, 21))
        self.pushButton_aim_app2_swRel_set.setObjectName("pushButton_aim_app2_swRel_set")
        self.pushButton_aim_app2_valid_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_valid_read.setGeometry(QtCore.QRect(70, 80, 71, 21))
        self.pushButton_aim_app2_valid_read.setObjectName("pushButton_aim_app2_valid_read")
        self.lineEdit_aim_app2_swRel_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_swRel_text.setGeometry(QtCore.QRect(160, 50, 101, 20))
        self.lineEdit_aim_app2_swRel_text.setObjectName("lineEdit_aim_app2_swRel_text")
        self.lineEdit_aim_app2_valid_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_valid_text.setGeometry(QtCore.QRect(160, 80, 101, 20))
        self.lineEdit_aim_app2_valid_text.setObjectName("lineEdit_aim_app2_valid_text")
        self.lineEdit_aim_app2_len_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_len_text.setGeometry(QtCore.QRect(430, 80, 101, 20))
        self.lineEdit_aim_app2_len_text.setObjectName("lineEdit_aim_app2_len_text")
        self.lineEdit_aim_app2_chk_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_chk_text.setGeometry(QtCore.QRect(430, 20, 101, 20))
        self.lineEdit_aim_app2_chk_text.setObjectName("lineEdit_aim_app2_chk_text")
        self.label_aim_app2_len = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_len.setGeometry(QtCore.QRect(280, 80, 54, 12))
        self.label_aim_app2_len.setObjectName("label_aim_app2_len")
        self.pushButton_aim_app2_chk_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_chk_read.setGeometry(QtCore.QRect(340, 20, 31, 21))
        self.pushButton_aim_app2_chk_read.setObjectName("pushButton_aim_app2_chk_read")
        self.lineEdit_aim_app2_swVer_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_swVer_text.setGeometry(QtCore.QRect(430, 50, 101, 20))
        self.lineEdit_aim_app2_swVer_text.setObjectName("lineEdit_aim_app2_swVer_text")
        self.pushButton_aim_app2_swVer_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_swVer_read.setGeometry(QtCore.QRect(340, 50, 31, 21))
        self.pushButton_aim_app2_swVer_read.setObjectName("pushButton_aim_app2_swVer_read")
        self.pushButton_aim_app2_swVer_set = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_swVer_set.setGeometry(QtCore.QRect(380, 50, 31, 21))
        self.pushButton_aim_app2_swVer_set.setObjectName("pushButton_aim_app2_swVer_set")
        self.pushButton_aim_app2_len_read = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_len_read.setGeometry(QtCore.QRect(340, 80, 71, 21))
        self.pushButton_aim_app2_len_read.setObjectName("pushButton_aim_app2_len_read")
        self.label_aim_app2_swVer = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_swVer.setGeometry(QtCore.QRect(280, 50, 54, 12))
        self.label_aim_app2_swVer.setObjectName("label_aim_app2_swVer")
        self.label_aim_app2_chk = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_chk.setGeometry(QtCore.QRect(280, 24, 54, 12))
        self.label_aim_app2_chk.setObjectName("label_aim_app2_chk")
        self.pushButton_aim_app2_chk_chk = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_chk_chk.setGeometry(QtCore.QRect(380, 20, 31, 21))
        self.pushButton_aim_app2_chk_chk.setObjectName("pushButton_aim_app2_chk_chk")
        self.label_aim_app2_file = QtWidgets.QLabel(self.groupBox_aim_app2)
        self.label_aim_app2_file.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_aim_app2_file.setObjectName("label_aim_app2_file")
        self.lineEdit_aim_app2_file_text = QtWidgets.QLineEdit(self.groupBox_aim_app2)
        self.lineEdit_aim_app2_file_text.setGeometry(QtCore.QRect(70, 110, 261, 20))
        self.lineEdit_aim_app2_file_text.setObjectName("lineEdit_aim_app2_file_text")
        self.pushButton_aim_app2_file_browse = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_file_browse.setGeometry(QtCore.QRect(350, 110, 71, 21))
        self.pushButton_aim_app2_file_browse.setObjectName("pushButton_aim_app2_file_browse")
        self.pushButton_aim_app2_file_update = QtWidgets.QPushButton(self.groupBox_aim_app2)
        self.pushButton_aim_app2_file_update.setGeometry(QtCore.QRect(450, 110, 71, 21))
        self.pushButton_aim_app2_file_update.setObjectName("pushButton_aim_app2_file_update")
        self.groupBox_aim_app1 = QtWidgets.QGroupBox(self.groupBox_aim_firmwareDown)
        self.groupBox_aim_app1.setGeometry(QtCore.QRect(10, 170, 551, 141))
        self.groupBox_aim_app1.setObjectName("groupBox_aim_app1")
        self.label_aim_app1_addr = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_addr.setGeometry(QtCore.QRect(10, 24, 54, 12))
        self.label_aim_app1_addr.setObjectName("label_aim_app1_addr")
        self.pushButton_aim_app1_addr_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_addr_read.setGeometry(QtCore.QRect(70, 20, 71, 21))
        self.pushButton_aim_app1_addr_read.setObjectName("pushButton_aim_app1_addr_read")
        self.lineEdit_aim_app1_addr_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_addr_text.setGeometry(QtCore.QRect(160, 20, 101, 20))
        self.lineEdit_aim_app1_addr_text.setObjectName("lineEdit_aim_app1_addr_text")
        self.label_aim_app1_swRel = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_swRel.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_aim_app1_swRel.setObjectName("label_aim_app1_swRel")
        self.label_aim_app1_valid = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_valid.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_aim_app1_valid.setObjectName("label_aim_app1_valid")
        self.pushButton_aim_app1_swRel_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_swRel_read.setGeometry(QtCore.QRect(70, 50, 31, 21))
        self.pushButton_aim_app1_swRel_read.setObjectName("pushButton_aim_app1_swRel_read")
        self.pushButton_aim_app1_swRel_set = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_swRel_set.setGeometry(QtCore.QRect(110, 50, 31, 21))
        self.pushButton_aim_app1_swRel_set.setObjectName("pushButton_aim_app1_swRel_set")
        self.pushButton_aim_app1_valid_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_valid_read.setGeometry(QtCore.QRect(70, 80, 71, 21))
        self.pushButton_aim_app1_valid_read.setObjectName("pushButton_aim_app1_valid_read")
        self.lineEdit_aim_app1_swRel_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_swRel_text.setGeometry(QtCore.QRect(160, 50, 101, 20))
        self.lineEdit_aim_app1_swRel_text.setObjectName("lineEdit_aim_app1_swRel_text")
        self.lineEdit_aim_app1_valid_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_valid_text.setGeometry(QtCore.QRect(160, 80, 101, 20))
        self.lineEdit_aim_app1_valid_text.setObjectName("lineEdit_aim_app1_valid_text")
        self.lineEdit_aim_app1_len_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_len_text.setGeometry(QtCore.QRect(430, 80, 101, 20))
        self.lineEdit_aim_app1_len_text.setObjectName("lineEdit_aim_app1_len_text")
        self.lineEdit_aim_app1_chk_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_chk_text.setGeometry(QtCore.QRect(430, 20, 101, 20))
        self.lineEdit_aim_app1_chk_text.setObjectName("lineEdit_aim_app1_chk_text")
        self.label_aim_app1_len = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_len.setGeometry(QtCore.QRect(280, 80, 54, 12))
        self.label_aim_app1_len.setObjectName("label_aim_app1_len")
        self.pushButton_aim_app1_chk_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_chk_read.setGeometry(QtCore.QRect(340, 20, 31, 21))
        self.pushButton_aim_app1_chk_read.setObjectName("pushButton_aim_app1_chk_read")
        self.lineEdit_aim_app1_swVer_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_swVer_text.setGeometry(QtCore.QRect(430, 50, 101, 20))
        self.lineEdit_aim_app1_swVer_text.setObjectName("lineEdit_aim_app1_swVer_text")
        self.pushButton_aim_app1_swVer_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_swVer_read.setGeometry(QtCore.QRect(340, 50, 31, 21))
        self.pushButton_aim_app1_swVer_read.setObjectName("pushButton_aim_app1_swVer_read")
        self.pushButton_aim_app1_swVer_set = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_swVer_set.setGeometry(QtCore.QRect(380, 50, 31, 21))
        self.pushButton_aim_app1_swVer_set.setObjectName("pushButton_aim_app1_swVer_set")
        self.pushButton_aim_app1_len_read = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_len_read.setGeometry(QtCore.QRect(340, 80, 71, 21))
        self.pushButton_aim_app1_len_read.setObjectName("pushButton_aim_app1_len_read")
        self.label_aim_app1_swVer = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_swVer.setGeometry(QtCore.QRect(280, 50, 54, 12))
        self.label_aim_app1_swVer.setObjectName("label_aim_app1_swVer")
        self.label_aim_app1_chk = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_chk.setGeometry(QtCore.QRect(280, 24, 54, 12))
        self.label_aim_app1_chk.setObjectName("label_aim_app1_chk")
        self.pushButton_aim_app1_chk_chk = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_chk_chk.setGeometry(QtCore.QRect(380, 20, 31, 21))
        self.pushButton_aim_app1_chk_chk.setObjectName("pushButton_aim_app1_chk_chk")
        self.label_aim_app1_file = QtWidgets.QLabel(self.groupBox_aim_app1)
        self.label_aim_app1_file.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_aim_app1_file.setObjectName("label_aim_app1_file")
        self.lineEdit_aim_app1_file_text = QtWidgets.QLineEdit(self.groupBox_aim_app1)
        self.lineEdit_aim_app1_file_text.setGeometry(QtCore.QRect(70, 110, 261, 20))
        self.lineEdit_aim_app1_file_text.setObjectName("lineEdit_aim_app1_file_text")
        self.pushButton_aim_app1_file_browse = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_file_browse.setGeometry(QtCore.QRect(350, 110, 71, 21))
        self.pushButton_aim_app1_file_browse.setObjectName("pushButton_aim_app1_file_browse")
        self.pushButton_aim_app1_file_update = QtWidgets.QPushButton(self.groupBox_aim_app1)
        self.pushButton_aim_app1_file_update.setGeometry(QtCore.QRect(450, 110, 71, 21))
        self.pushButton_aim_app1_file_update.setObjectName("pushButton_aim_app1_file_update")
        self.groupBox_bbo_BatchBurnOperation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_bbo_BatchBurnOperation.setGeometry(QtCore.QRect(580, 620, 571, 81))
        self.groupBox_bbo_BatchBurnOperation.setObjectName("groupBox_bbo_BatchBurnOperation")
        self.pushButton_bbo_burn_fac_app = QtWidgets.QPushButton(self.groupBox_bbo_BatchBurnOperation)
        self.pushButton_bbo_burn_fac_app.setGeometry(QtCore.QRect(10, 20, 231, 23))
        self.pushButton_bbo_burn_fac_app.setObjectName("pushButton_bbo_burn_fac_app")
        self.pushButton_bbo_burn_bc_fac_app = QtWidgets.QPushButton(self.groupBox_bbo_BatchBurnOperation)
        self.pushButton_bbo_burn_bc_fac_app.setGeometry(QtCore.QRect(320, 20, 231, 23))
        self.pushButton_bbo_burn_bc_fac_app.setObjectName("pushButton_bbo_burn_bc_fac_app")
        self.lineEdit_bbo_devCode_text = QtWidgets.QLineEdit(self.groupBox_bbo_BatchBurnOperation)
        self.lineEdit_bbo_devCode_text.setGeometry(QtCore.QRect(70, 50, 181, 20))
        self.lineEdit_bbo_devCode_text.setObjectName("lineEdit_bbo_devCode_text")
        self.label_bbo_codeFix = QtWidgets.QLabel(self.groupBox_bbo_BatchBurnOperation)
        self.label_bbo_codeFix.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_bbo_codeFix.setObjectName("label_bbo_codeFix")
        self.lineEdit_bbo_maxNumber_text = QtWidgets.QLineEdit(self.groupBox_bbo_BatchBurnOperation)
        self.lineEdit_bbo_maxNumber_text.setGeometry(QtCore.QRect(370, 50, 41, 20))
        self.lineEdit_bbo_maxNumber_text.setObjectName("lineEdit_bbo_maxNumber_text")
        self.label_bbo_maxNumber = QtWidgets.QLabel(self.groupBox_bbo_BatchBurnOperation)
        self.label_bbo_maxNumber.setGeometry(QtCore.QRect(300, 50, 91, 16))
        self.label_bbo_maxNumber.setObjectName("label_bbo_maxNumber")
        self.checkBox_bbo_batchModeSelection = QtWidgets.QCheckBox(self.groupBox_bbo_BatchBurnOperation)
        self.checkBox_bbo_batchModeSelection.setGeometry(QtCore.QRect(480, 50, 71, 16))
        self.checkBox_bbo_batchModeSelection.setObjectName("checkBox_bbo_batchModeSelection")
        self.groupBox_cloudCon = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_cloudCon.setGeometry(QtCore.QRect(10, 10, 561, 141))
        self.groupBox_cloudCon.setObjectName("groupBox_cloudCon")
        self.lineEdit_cloudCon_label_apply_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_label_apply_text.setGeometry(QtCore.QRect(200, 110, 351, 20))
        self.lineEdit_cloudCon_label_apply_text.setObjectName("lineEdit_cloudCon_label_apply_text")
        self.lineEdit_cloudCon_apply_number_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_apply_number_text.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.lineEdit_cloudCon_apply_number_text.setObjectName("lineEdit_cloudCon_apply_number_text")
        self.pushButton_cloudCon_par_set = QtWidgets.QPushButton(self.groupBox_cloudCon)
        self.pushButton_cloudCon_par_set.setGeometry(QtCore.QRect(10, 110, 81, 23))
        self.pushButton_cloudCon_par_set.setObjectName("pushButton_cloudCon_par_set")
        self.lineEdit_cloudCon_ipAddr_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_ipAddr_text.setGeometry(QtCore.QRect(220, 20, 151, 20))
        self.lineEdit_cloudCon_ipAddr_text.setObjectName("lineEdit_cloudCon_ipAddr_text")
        self.label_cloudCon_apply_number = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_apply_number.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.label_cloudCon_apply_number.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_apply_number.setObjectName("label_cloudCon_apply_number")
        self.label_cloudCon_ipAddr = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_ipAddr.setGeometry(QtCore.QRect(150, 20, 91, 23))
        self.label_cloudCon_ipAddr.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_ipAddr.setObjectName("label_cloudCon_ipAddr")
        self.lineEdit_cloudCon_facCode_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_facCode_text.setGeometry(QtCore.QRect(440, 20, 111, 20))
        self.lineEdit_cloudCon_facCode_text.setObjectName("lineEdit_cloudCon_facCode_text")
        self.label_cloudCon_facCode = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_facCode.setGeometry(QtCore.QRect(390, 20, 91, 23))
        self.label_cloudCon_facCode.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_facCode.setObjectName("label_cloudCon_facCode")
        self.lineEdit_cloudCon_pdCode_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_pdCode_text.setGeometry(QtCore.QRect(80, 50, 41, 20))
        self.lineEdit_cloudCon_pdCode_text.setObjectName("lineEdit_cloudCon_pdCode_text")
        self.label_cloudCon_pdCode = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_pdCode.setGeometry(QtCore.QRect(40, 50, 91, 23))
        self.label_cloudCon_pdCode.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_pdCode.setObjectName("label_cloudCon_pdCode")
        self.lineEdit_cloudCon_pjCode_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_pjCode_text.setGeometry(QtCore.QRect(200, 50, 51, 20))
        self.lineEdit_cloudCon_pjCode_text.setObjectName("lineEdit_cloudCon_pjCode_text")
        self.lineEdit_cloudCon_pdType_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_pdType_text.setGeometry(QtCore.QRect(470, 50, 81, 20))
        self.lineEdit_cloudCon_pdType_text.setObjectName("lineEdit_cloudCon_pdType_text")
        self.label_cloudCon_pdType = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_pdType.setGeometry(QtCore.QRect(430, 50, 91, 23))
        self.label_cloudCon_pdType.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_pdType.setObjectName("label_cloudCon_pdType")
        self.lineEdit_cloudCon_userAccount_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_userAccount_text.setGeometry(QtCore.QRect(90, 80, 101, 20))
        self.lineEdit_cloudCon_userAccount_text.setObjectName("lineEdit_cloudCon_userAccount_text")
        self.label_cloudCon_userAccount = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_userAccount.setGeometry(QtCore.QRect(20, 80, 91, 23))
        self.label_cloudCon_userAccount.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_userAccount.setObjectName("label_cloudCon_userAccount")
        self.lineEdit_cloudCon_passwd_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_passwd_text.setGeometry(QtCore.QRect(270, 80, 91, 20))
        self.lineEdit_cloudCon_passwd_text.setObjectName("lineEdit_cloudCon_passwd_text")
        self.label_cloudCon_passwd = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_passwd.setGeometry(QtCore.QRect(230, 80, 91, 23))
        self.label_cloudCon_passwd.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_passwd.setObjectName("label_cloudCon_passwd")
        self.lineEdit_cloudCon_formalFlag_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_formalFlag_text.setGeometry(QtCore.QRect(460, 80, 91, 20))
        self.lineEdit_cloudCon_formalFlag_text.setObjectName("lineEdit_cloudCon_formalFlag_text")
        self.label_cloudCon_formalFlag = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_formalFlag.setGeometry(QtCore.QRect(390, 80, 91, 23))
        self.label_cloudCon_formalFlag.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_formalFlag.setObjectName("label_cloudCon_formalFlag")
        self.pushButton_cloudCon_label_apply = QtWidgets.QPushButton(self.groupBox_cloudCon)
        self.pushButton_cloudCon_label_apply.setGeometry(QtCore.QRect(110, 110, 81, 23))
        self.pushButton_cloudCon_label_apply.setObjectName("pushButton_cloudCon_label_apply")
        self.label_cloudCon_userCode = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_userCode.setGeometry(QtCore.QRect(270, 50, 91, 23))
        self.label_cloudCon_userCode.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_userCode.setObjectName("label_cloudCon_userCode")
        self.lineEdit_cloudCon_userCode_text = QtWidgets.QLineEdit(self.groupBox_cloudCon)
        self.lineEdit_cloudCon_userCode_text.setGeometry(QtCore.QRect(320, 50, 51, 20))
        self.lineEdit_cloudCon_userCode_text.setObjectName("lineEdit_cloudCon_userCode_text")
        self.label_cloudCon_pjCode = QtWidgets.QLabel(self.groupBox_cloudCon)
        self.label_cloudCon_pjCode.setGeometry(QtCore.QRect(160, 50, 91, 23))
        self.label_cloudCon_pjCode.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cloudCon_pjCode.setObjectName("label_cloudCon_pjCode")
        self.groupBox_ihuConn = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ihuConn.setGeometry(QtCore.QRect(580, 10, 571, 121))
        self.groupBox_ihuConn.setObjectName("groupBox_ihuConn")
        self.pushButton_ihuCon_conn = QtWidgets.QPushButton(self.groupBox_ihuConn)
        self.pushButton_ihuCon_conn.setGeometry(QtCore.QRect(10, 70, 51, 21))
        self.pushButton_ihuCon_conn.setObjectName("pushButton_ihuCon_conn")
        self.radioButton_ihuCon_port_eth = QtWidgets.QRadioButton(self.groupBox_ihuConn)
        self.radioButton_ihuCon_port_eth.setGeometry(QtCore.QRect(11, 54, 51, 16))
        self.radioButton_ihuCon_port_eth.setObjectName("radioButton_ihuCon_port_eth")
        self.radioButton_ihuCon_port_sps = QtWidgets.QRadioButton(self.groupBox_ihuConn)
        self.radioButton_ihuCon_port_sps.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton_ihuCon_port_sps.setObjectName("radioButton_ihuCon_port_sps")
        self.radioButton_ihuCon_port_can = QtWidgets.QRadioButton(self.groupBox_ihuConn)
        self.radioButton_ihuCon_port_can.setGeometry(QtCore.QRect(10, 37, 51, 16))
        self.radioButton_ihuCon_port_can.setChecked(True)
        self.radioButton_ihuCon_port_can.setObjectName("radioButton_ihuCon_port_can")
        self.pushButton_ihuCon_disc = QtWidgets.QPushButton(self.groupBox_ihuConn)
        self.pushButton_ihuCon_disc.setGeometry(QtCore.QRect(10, 93, 51, 21))
        self.pushButton_ihuCon_disc.setObjectName("pushButton_ihuCon_disc")
        self.groupBox_ihuConn_canParSet = QtWidgets.QGroupBox(self.groupBox_ihuConn)
        self.groupBox_ihuConn_canParSet.setGeometry(QtCore.QRect(60, 10, 501, 101))
        self.groupBox_ihuConn_canParSet.setObjectName("groupBox_ihuConn_canParSet")
        self.label_ihuConn_canParSet_productType = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_productType.setGeometry(QtCore.QRect(10, 22, 61, 16))
        self.label_ihuConn_canParSet_productType.setObjectName("label_ihuConn_canParSet_productType")
        self.comboBox_ihuConn_canParSet_productType = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_productType.setGeometry(QtCore.QRect(64, 20, 81, 22))
        self.comboBox_ihuConn_canParSet_productType.setObjectName("comboBox_ihuConn_canParSet_productType")
        self.comboBox_ihuConn_canParSet_productType.addItem("")
        self.comboBox_ihuConn_canParSet_productType.addItem("")
        self.comboBox_ihuConn_canParSet_index = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_index.setGeometry(QtCore.QRect(200, 20, 51, 22))
        self.comboBox_ihuConn_canParSet_index.setObjectName("comboBox_ihuConn_canParSet_index")
        self.comboBox_ihuConn_canParSet_index.addItem("")
        self.comboBox_ihuConn_canParSet_index.addItem("")
        self.comboBox_ihuConn_canParSet_index.addItem("")
        self.comboBox_ihuConn_canParSet_index.addItem("")
        self.label_ihuConn_canParSet_index = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_index.setGeometry(QtCore.QRect(156, 22, 41, 16))
        self.label_ihuConn_canParSet_index.setObjectName("label_ihuConn_canParSet_index")
        self.comboBox_ihuConn_canParSet_canNbr = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_canNbr.setGeometry(QtCore.QRect(330, 20, 31, 22))
        self.comboBox_ihuConn_canParSet_canNbr.setObjectName("comboBox_ihuConn_canParSet_canNbr")
        self.comboBox_ihuConn_canParSet_canNbr.addItem("")
        self.comboBox_ihuConn_canParSet_canNbr.addItem("")
        self.label_ihuConn_canParSet_canNbr = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_canNbr.setGeometry(QtCore.QRect(260, 22, 61, 16))
        self.label_ihuConn_canParSet_canNbr.setObjectName("label_ihuConn_canParSet_canNbr")
        self.label_ihuConn_canParSet_rcvCode = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_rcvCode.setGeometry(QtCore.QRect(10, 52, 51, 16))
        self.label_ihuConn_canParSet_rcvCode.setObjectName("label_ihuConn_canParSet_rcvCode")
        self.lineEdit_ihuConn_canParSet_rcvCode_text = QtWidgets.QLineEdit(self.groupBox_ihuConn_canParSet)
        self.lineEdit_ihuConn_canParSet_rcvCode_text.setGeometry(QtCore.QRect(64, 50, 81, 20))
        self.lineEdit_ihuConn_canParSet_rcvCode_text.setObjectName("lineEdit_ihuConn_canParSet_rcvCode_text")
        self.lineEdit_ihuConn_canParSet_timer0_text = QtWidgets.QLineEdit(self.groupBox_ihuConn_canParSet)
        self.lineEdit_ihuConn_canParSet_timer0_text.setGeometry(QtCore.QRect(230, 50, 21, 20))
        self.lineEdit_ihuConn_canParSet_timer0_text.setObjectName("lineEdit_ihuConn_canParSet_timer0_text")
        self.label_ihuConn_canParSet_timer0 = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_timer0.setGeometry(QtCore.QRect(156, 52, 71, 16))
        self.label_ihuConn_canParSet_timer0.setObjectName("label_ihuConn_canParSet_timer0")
        self.lineEdit_ihuConn_canParSet_maskCode_text = QtWidgets.QLineEdit(self.groupBox_ihuConn_canParSet)
        self.lineEdit_ihuConn_canParSet_maskCode_text.setGeometry(QtCore.QRect(64, 80, 81, 20))
        self.lineEdit_ihuConn_canParSet_maskCode_text.setObjectName("lineEdit_ihuConn_canParSet_maskCode_text")
        self.label_ihuConn_canParSet_maskCode = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_maskCode.setGeometry(QtCore.QRect(10, 82, 51, 16))
        self.label_ihuConn_canParSet_maskCode.setObjectName("label_ihuConn_canParSet_maskCode")
        self.lineEdit_ihuConn_canParSet_timer1_text = QtWidgets.QLineEdit(self.groupBox_ihuConn_canParSet)
        self.lineEdit_ihuConn_canParSet_timer1_text.setGeometry(QtCore.QRect(230, 80, 21, 20))
        self.lineEdit_ihuConn_canParSet_timer1_text.setObjectName("lineEdit_ihuConn_canParSet_timer1_text")
        self.label_ihuConn_canParSet_timer1 = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_timer1.setGeometry(QtCore.QRect(156, 82, 71, 16))
        self.label_ihuConn_canParSet_timer1.setObjectName("label_ihuConn_canParSet_timer1")
        self.comboBox_ihuConn_canParSet_filter = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_filter.setGeometry(QtCore.QRect(330, 50, 61, 22))
        self.comboBox_ihuConn_canParSet_filter.setObjectName("comboBox_ihuConn_canParSet_filter")
        self.comboBox_ihuConn_canParSet_filter.addItem("")
        self.comboBox_ihuConn_canParSet_filter.addItem("")
        self.comboBox_ihuConn_canParSet_filter.addItem("")
        self.label_ihuConn_canParSet_filter = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_filter.setGeometry(QtCore.QRect(260, 52, 61, 16))
        self.label_ihuConn_canParSet_filter.setObjectName("label_ihuConn_canParSet_filter")
        self.comboBox_ihuConn_canParSet_workMode = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_workMode.setGeometry(QtCore.QRect(330, 80, 51, 22))
        self.comboBox_ihuConn_canParSet_workMode.setObjectName("comboBox_ihuConn_canParSet_workMode")
        self.comboBox_ihuConn_canParSet_workMode.addItem("")
        self.comboBox_ihuConn_canParSet_workMode.addItem("")
        self.comboBox_ihuConn_canParSet_workMode.addItem("")
        self.label_ihuConn_canParSet_workMode = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_workMode.setGeometry(QtCore.QRect(260, 80, 61, 16))
        self.label_ihuConn_canParSet_workMode.setObjectName("label_ihuConn_canParSet_workMode")
        self.comboBox_ihuConn_canParSet_frameType = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_frameType.setGeometry(QtCore.QRect(440, 20, 61, 22))
        self.comboBox_ihuConn_canParSet_frameType.setObjectName("comboBox_ihuConn_canParSet_frameType")
        self.comboBox_ihuConn_canParSet_frameType.addItem("")
        self.comboBox_ihuConn_canParSet_frameType.addItem("")
        self.label_ihuConn_canParSet_frameType = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_frameType.setGeometry(QtCore.QRect(400, 20, 41, 16))
        self.label_ihuConn_canParSet_frameType.setObjectName("label_ihuConn_canParSet_frameType")
        self.comboBox_ihuConn_canParSet_frameFormat = QtWidgets.QComboBox(self.groupBox_ihuConn_canParSet)
        self.comboBox_ihuConn_canParSet_frameFormat.setGeometry(QtCore.QRect(440, 50, 61, 22))
        self.comboBox_ihuConn_canParSet_frameFormat.setObjectName("comboBox_ihuConn_canParSet_frameFormat")
        self.comboBox_ihuConn_canParSet_frameFormat.addItem("")
        self.comboBox_ihuConn_canParSet_frameFormat.addItem("")
        self.label_ihuConn_canParSet_frameFormat = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_frameFormat.setGeometry(QtCore.QRect(400, 50, 41, 16))
        self.label_ihuConn_canParSet_frameFormat.setObjectName("label_ihuConn_canParSet_frameFormat")
        self.label_ihuConn_canParSet_frameId = QtWidgets.QLabel(self.groupBox_ihuConn_canParSet)
        self.label_ihuConn_canParSet_frameId.setGeometry(QtCore.QRect(390, 80, 51, 20))
        self.label_ihuConn_canParSet_frameId.setObjectName("label_ihuConn_canParSet_frameId")
        self.lineEdit_ihuConn_canParSet_frameId_text = QtWidgets.QLineEdit(self.groupBox_ihuConn_canParSet)
        self.lineEdit_ihuConn_canParSet_frameId_text.setGeometry(QtCore.QRect(440, 80, 61, 20))
        self.lineEdit_ihuConn_canParSet_frameId_text.setObjectName("lineEdit_ihuConn_canParSet_frameId_text")
        ObjFmpt2MainForm.setCentralWidget(self.centralwidget)
        self.ObjFmpt2Menubar = QtWidgets.QMenuBar(ObjFmpt2MainForm)
        self.ObjFmpt2Menubar.setGeometry(QtCore.QRect(0, 0, 1420, 23))
        self.ObjFmpt2Menubar.setObjectName("ObjFmpt2Menubar")
        self.menu = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.ObjFmpt2Menubar)
        self.menu_7.setObjectName("menu_7")
        ObjFmpt2MainForm.setMenuBar(self.ObjFmpt2Menubar)
        self.ObjFmpt2StatusBar = QtWidgets.QStatusBar(ObjFmpt2MainForm)
        self.ObjFmpt2StatusBar.setMouseTracking(True)
        self.ObjFmpt2StatusBar.setTabletTracking(True)
        self.ObjFmpt2StatusBar.setAcceptDrops(True)
        self.ObjFmpt2StatusBar.setAutoFillBackground(True)
        self.ObjFmpt2StatusBar.setObjectName("ObjFmpt2StatusBar")
        ObjFmpt2MainForm.setStatusBar(self.ObjFmpt2StatusBar)
        self.ObjFmpt2Menubar.addAction(self.menu.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_2.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_3.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_4.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_5.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_6.menuAction())
        self.ObjFmpt2Menubar.addAction(self.menu_7.menuAction())

        self.retranslateUi(ObjFmpt2MainForm)
        self.pushButton_cloudCon_par_set.clicked.connect(ObjFmpt2MainForm.slot_cloudCon_par_set)
        self.pushButton_keo_cfgFile_Browse.clicked.connect(ObjFmpt2MainForm.slot_keo_cfgFile_Browse)
        self.pushButton_keo_byteopr_read.clicked.connect(ObjFmpt2MainForm.slot_keo_byteopr_read)
        self.pushButton_keo_byteopr_write.clicked.connect(ObjFmpt2MainForm.slot_keo_byteopr_write)
        self.pushButton_fio_file_browse.clicked.connect(ObjFmpt2MainForm.slot_fio_file_browse)
        self.pushButton_fio_file_save.clicked.connect(ObjFmpt2MainForm.slot_fio_file_save)
        self.pushButton_fio_file_load.clicked.connect(ObjFmpt2MainForm.slot_fio_file_load)
        self.pushButton_ihuCon_conn.clicked.connect(ObjFmpt2MainForm.slot_ihuCon_conn)
        self.pushButton_aim_fac_addr_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_addr_read)
        self.pushButton_aim_fac_chk_chk.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_chk_chk)
        self.pushButton_aim_fac_chk_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_chk_read)
        self.pushButton_aim_fac_swRel_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_swRel_read)
        self.pushButton_aim_fac_swRel_set.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_swRel_set)
        self.pushButton_aim_fac_valid_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_valid_read)
        self.pushButton_aim_fac_swVer_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_swVer_read)
        self.pushButton_aim_fac_swVer_set.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_swVer_set)
        self.pushButton_aim_fac_file_browse.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_file_browse)
        self.pushButton_aim_fac_file_update.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_file_update)
        self.pushButton_aim_app1_addr_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_addr_read)
        self.pushButton_aim_app1_swRel_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_swRel_read)
        self.pushButton_aim_app1_swRel_set.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_swRel_set)
        self.pushButton_aim_app1_valid_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_valid_read)
        self.pushButton_aim_app1_chk_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_chk_read)
        self.pushButton_aim_app1_chk_chk.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_chk_chk)
        self.pushButton_aim_app1_swVer_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_swVer_read)
        self.pushButton_aim_app1_swVer_set.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_swVer_set)
        self.pushButton_aim_fac_len_read.clicked.connect(ObjFmpt2MainForm.slot_aim_fac_len_read)
        self.pushButton_aim_app1_len_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_len_read)
        self.pushButton_aim_app1_file_browse.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_file_browse)
        self.pushButton_aim_app1_file_update.clicked.connect(ObjFmpt2MainForm.slot_aim_app1_file_update)
        self.pushButton_aim_app2_addr_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_addr_read)
        self.pushButton_aim_app2_chk_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_chk_read)
        self.pushButton_aim_app2_chk_chk.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_chk_chk)
        self.pushButton_aim_app2_swRel_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_swRel_read)
        self.pushButton_aim_app2_swRel_set.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_swRel_set)
        self.pushButton_aim_app2_swVer_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_swVer_read)
        self.pushButton_aim_app2_swVer_set.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_swVer_set)
        self.pushButton_aim_app2_valid_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_valid_read)
        self.pushButton_aim_app2_len_read.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_len_read)
        self.pushButton_aim_app2_file_browse.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_file_browse)
        self.pushButton_aim_app2_file_update.clicked.connect(ObjFmpt2MainForm.slot_aim_app2_file_update)
        self.pushButton_bbo_burn_fac_app.clicked.connect(ObjFmpt2MainForm.slot_bbo_burn_fac_app)
        self.pushButton_bbo_burn_bc_fac_app.clicked.connect(ObjFmpt2MainForm.slot_bbo_burn_bc_fac_app)
        self.pushButton_keo_swUpgradeFlag_write.clicked.connect(ObjFmpt2MainForm.slot_keo_swUpgradeFlag_write)
        self.pushButton_keo_hwPemId_read.clicked.connect(ObjFmpt2MainForm.slot_keo_hwPemId_read)
        self.pushButton_keo_hwPemId_write.clicked.connect(ObjFmpt2MainForm.slot_keo_hwPemId_write)
        self.pushButton_keo_swRelId_read.clicked.connect(ObjFmpt2MainForm.slot_keo_swRelId_read)
        self.pushButton_keo_swRelId_write.clicked.connect(ObjFmpt2MainForm.slot_keo_swRelId_write)
        self.pushButton_keo_swVerId_read.clicked.connect(ObjFmpt2MainForm.slot_keo_swVerId_read)
        self.pushButton_keo_swVerId_write.clicked.connect(ObjFmpt2MainForm.slot_keo_swVerId_write)
        self.pushButton_keo_swUpgPollId_read.clicked.connect(ObjFmpt2MainForm.slot_keo_swUpgPollId_read)
        self.pushButton_keo_swUpgPollId_write.clicked.connect(ObjFmpt2MainForm.slot_keo_swUpgPollId_write)
        self.pushButton_keo_bootIndex_read.clicked.connect(ObjFmpt2MainForm.slot_keo_bootIndex_read)
        self.pushButton_keo_bootInde_write.clicked.connect(ObjFmpt2MainForm.slot_keo_bootIndex_write)
        self.pushButton_keo_bootAreaMax_read.clicked.connect(ObjFmpt2MainForm.slot_keo_bootAreaMax_read)
        self.pushButton_keo_bootAreaMax_write.clicked.connect(ObjFmpt2MainForm.slot_keo_bootAreaMax_write)
        self.pushButton_keo_cypherKey_read.clicked.connect(ObjFmpt2MainForm.slot_keo_cypherKey_read)
        self.pushButton_keo_cypherKey_write.clicked.connect(ObjFmpt2MainForm.slot_keo_cypherKey_write)
        self.pushButton_keo_hwType_read.clicked.connect(ObjFmpt2MainForm.slot_keo_hwType_read)
        self.pushButton_keo_hwType_write.clicked.connect(ObjFmpt2MainForm.slot_keo_hwType_write)
        self.pushButton_keo_swUpgradeFlag_read.clicked.connect(ObjFmpt2MainForm.slot_keo_swUpgradeFlag_read)
        self.pushButton_keo_equLable_read.clicked.connect(ObjFmpt2MainForm.slot_keo_equLable_read)
        self.pushButton_keo_equLable_write.clicked.connect(ObjFmpt2MainForm.slot_keo_equLable_write)
        self.pushButton_oli_clear.clicked.connect(ObjFmpt2MainForm.slot_oli_clear)
        self.pushButton_cloudCon_label_apply.clicked.connect(ObjFmpt2MainForm.slot_cloudCon_label_apply)
        self.pushButton_oli_test.clicked.connect(ObjFmpt2MainForm.slot_oli_test)
        self.pushButton_keo_cfgFile_LoadFile.clicked.connect(ObjFmpt2MainForm.slot_keo_cfgFile_LoadFile)
        self.pushButton_keo_cfgFile_SaveFile.clicked.connect(ObjFmpt2MainForm.slot_keo_cfgFile_SaveFile)
        self.pushButton_keo_cfgFile_ReadAllFromHw.clicked.connect(ObjFmpt2MainForm.slot_keo_cfgFile_ReadAllFromHw)
        self.pushButton_keo_cfgFile_WriteAllToHw.clicked.connect(ObjFmpt2MainForm.slot_keo_cfgFile_WriteAllToHw)
        self.pushButton_ihuCon_disc.clicked.connect(ObjFmpt2MainForm.slot_ihuCon_disc)
        QtCore.QMetaObject.connectSlotsByName(ObjFmpt2MainForm)

    def retranslateUi(self, ObjFmpt2MainForm):
        _translate = QtCore.QCoreApplication.translate
        ObjFmpt2MainForm.setWindowTitle(_translate("ObjFmpt2MainForm", "FMPT2工厂生产工具"))
        self.groupBox_oli_OperationLogInfo.setTitle(_translate("ObjFmpt2MainForm", "OPERATION LOG INFO"))
        self.textEdit_OprLogInfo.setHtml(_translate("ObjFmpt2MainForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; SND 0x1111 to Hardware</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; RCV 0x2222 from Hardware</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; ERR info get from reading file</p></body></html>"))
        self.pushButton_oli_clear.setText(_translate("ObjFmpt2MainForm", "CLEAR"))
        self.pushButton_oli_test.setText(_translate("ObjFmpt2MainForm", "TEST"))
        self.groupBox_keo_KeyElementOperation.setTitle(_translate("ObjFmpt2MainForm", "控参操作"))
        self.label_keo_hwType.setText(_translate("ObjFmpt2MainForm", "hwType"))
        self.pushButton_keo_hwType_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_hwType_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_hwType.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.label_keo_hwPemId.setText(_translate("ObjFmpt2MainForm", "hwPemId"))
        self.pushButton_keo_hwPemId_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_hwPemId_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_hwPemId.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.label_keo_swRelId.setText(_translate("ObjFmpt2MainForm", "swRelId"))
        self.pushButton_keo_swRelId_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_swRelId_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_swRelId.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.label_keo_swVerId.setText(_translate("ObjFmpt2MainForm", "swVerId"))
        self.pushButton_keo_swVerId_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_swVerId_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_swVerId.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.label_keo_swUpgradeFlag.setText(_translate("ObjFmpt2MainForm", "swUpgradeFlag"))
        self.pushButton_keo_swUpgradeFlag_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_swUpgradeFlag_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_swUpgradeFlag.setText(_translate("ObjFmpt2MainForm", "0x01"))
        self.label_keo_swUpgPollId.setText(_translate("ObjFmpt2MainForm", "swUpgPollId"))
        self.pushButton_keo_swUpgPollId_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_swUpgPollId_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_swUpgPollId.setText(_translate("ObjFmpt2MainForm", "0x01"))
        self.label_keo_bootIndex.setText(_translate("ObjFmpt2MainForm", "bootIndex"))
        self.pushButton_keo_bootIndex_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_bootInde_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_bootIndex.setText(_translate("ObjFmpt2MainForm", "0x01"))
        self.label_keo_bootAreaMax.setText(_translate("ObjFmpt2MainForm", "bootAreaMax"))
        self.pushButton_keo_bootAreaMax_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_bootAreaMax_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_bootAreaMax.setText(_translate("ObjFmpt2MainForm", "0x01"))
        self.label_keo_cypherKey.setText(_translate("ObjFmpt2MainForm", "cypherKey"))
        self.pushButton_keo_cypherKey_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_cypherKey_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_cypherKey.setText(_translate("ObjFmpt2MainForm", "0x000102030405060708090A0B0C0D0E0F"))
        self.groupBox_keo_LoadBootcfg.setTitle(_translate("ObjFmpt2MainForm", "配置文件"))
        self.label_keo_cfgFile.setText(_translate("ObjFmpt2MainForm", "CFG FILE"))
        self.pushButton_keo_cfgFile_Browse.setText(_translate("ObjFmpt2MainForm", "BROWSE"))
        self.lineEdit_keo_cfgFile.setText(_translate("ObjFmpt2MainForm", "d:/bootcfg.txt"))
        self.pushButton_keo_cfgFile_LoadFile.setText(_translate("ObjFmpt2MainForm", "LOAD FILE"))
        self.pushButton_keo_cfgFile_SaveFile.setText(_translate("ObjFmpt2MainForm", "SAVE FILE"))
        self.pushButton_keo_cfgFile_ReadAllFromHw.setText(_translate("ObjFmpt2MainForm", "READ ALL FROM HARDWARE"))
        self.pushButton_keo_cfgFile_WriteAllToHw.setText(_translate("ObjFmpt2MainForm", "WRITE ALL TO HARDWARE"))
        self.groupBox_keo_SingleByteOpr.setTitle(_translate("ObjFmpt2MainForm", "FLASH访问"))
        self.label_keo_byteopr_address.setText(_translate("ObjFmpt2MainForm", "ADDRESS"))
        self.lineEdit_keo_byteopr_address.setText(_translate("ObjFmpt2MainForm", "0x80001234"))
        self.radioButton_keo_byteopr_byte.setText(_translate("ObjFmpt2MainForm", "BYTE"))
        self.radioButton_keo_byteopr_short.setText(_translate("ObjFmpt2MainForm", "SHORT"))
        self.radioButton_keo_byteopr_int.setText(_translate("ObjFmpt2MainForm", "INT"))
        self.pushButton_keo_byteopr_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_byteopr_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_byteopr_result.setText(_translate("ObjFmpt2MainForm", "ABCD"))
        self.label_keo_equLable.setText(_translate("ObjFmpt2MainForm", "equLable"))
        self.pushButton_keo_equLable_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_keo_equLable_write.setText(_translate("ObjFmpt2MainForm", "WRITE"))
        self.lineEdit_keo_equLable.setText(_translate("ObjFmpt2MainForm", "IHU_G5008GTJY_RND01"))
        self.groupBox_fio_FullImageOperation.setTitle(_translate("ObjFmpt2MainForm", "镜像操作"))
        self.pushButton_fio_file_browse.setText(_translate("ObjFmpt2MainForm", "BROWSE"))
        self.lineEdit_fio_file_dir.setText(_translate("ObjFmpt2MainForm", "d:/a.img"))
        self.pushButton_fio_file_save.setText(_translate("ObjFmpt2MainForm", "SAVE IMAGE FROM FLASH TO DISK"))
        self.pushButton_fio_file_load.setText(_translate("ObjFmpt2MainForm", "LOAD IMAGE FROM DISK TO FLASH"))
        self.groupBox_aim_firmwareDown.setTitle(_translate("ObjFmpt2MainForm", "固件下载"))
        self.groupBox_aim_fac.setTitle(_translate("ObjFmpt2MainForm", "FACTORY LOAD"))
        self.label_aim_fac_addr.setText(_translate("ObjFmpt2MainForm", "ADDRESS"))
        self.pushButton_aim_fac_addr_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_fac_addr_text.setText(_translate("ObjFmpt2MainForm", "0x80001234"))
        self.label_aim_fac_swRel.setText(_translate("ObjFmpt2MainForm", "swRel"))
        self.label_aim_fac_valid.setText(_translate("ObjFmpt2MainForm", "valid"))
        self.pushButton_aim_fac_swRel_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_fac_swRel_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_fac_valid_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_fac_swRel_text.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.lineEdit_aim_fac_valid_text.setText(_translate("ObjFmpt2MainForm", "0x5678"))
        self.lineEdit_aim_fac_len_text.setText(_translate("ObjFmpt2MainForm", "0x12345678"))
        self.lineEdit_aim_fac_chk_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.label_aim_fac_len.setText(_translate("ObjFmpt2MainForm", "Len"))
        self.pushButton_aim_fac_chk_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_fac_swVer_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.pushButton_aim_fac_swVer_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_fac_swVer_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_fac_len_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.label_aim_fac_swVer.setText(_translate("ObjFmpt2MainForm", "swVer"))
        self.label_aim_fac_chk.setText(_translate("ObjFmpt2MainForm", "CHECKSUM"))
        self.pushButton_aim_fac_chk_chk.setText(_translate("ObjFmpt2MainForm", "CHK"))
        self.label_aim_fac_file.setText(_translate("ObjFmpt2MainForm", ".BIN FILE"))
        self.lineEdit_aim_fac_file_text.setText(_translate("ObjFmpt2MainForm", "d:/fac.bin"))
        self.pushButton_aim_fac_file_browse.setText(_translate("ObjFmpt2MainForm", "BROWSE"))
        self.pushButton_aim_fac_file_update.setText(_translate("ObjFmpt2MainForm", "UPDATE"))
        self.groupBox_aim_app2.setTitle(_translate("ObjFmpt2MainForm", "APP2 LOAD"))
        self.label_aim_app2_addr.setText(_translate("ObjFmpt2MainForm", "ADDRESS"))
        self.pushButton_aim_app2_addr_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app2_addr_text.setText(_translate("ObjFmpt2MainForm", "0x80001234"))
        self.label_aim_app2_swRel.setText(_translate("ObjFmpt2MainForm", "swRel"))
        self.label_aim_app2_valid.setText(_translate("ObjFmpt2MainForm", "valid"))
        self.pushButton_aim_app2_swRel_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_app2_swRel_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_app2_valid_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app2_swRel_text.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.lineEdit_aim_app2_valid_text.setText(_translate("ObjFmpt2MainForm", "0x5678"))
        self.lineEdit_aim_app2_len_text.setText(_translate("ObjFmpt2MainForm", "0x12345678"))
        self.lineEdit_aim_app2_chk_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.label_aim_app2_len.setText(_translate("ObjFmpt2MainForm", "Len"))
        self.pushButton_aim_app2_chk_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app2_swVer_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.pushButton_aim_app2_swVer_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_app2_swVer_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_app2_len_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.label_aim_app2_swVer.setText(_translate("ObjFmpt2MainForm", "swVer"))
        self.label_aim_app2_chk.setText(_translate("ObjFmpt2MainForm", "CHECKSUM"))
        self.pushButton_aim_app2_chk_chk.setText(_translate("ObjFmpt2MainForm", "CHK"))
        self.label_aim_app2_file.setText(_translate("ObjFmpt2MainForm", ".BIN FILE"))
        self.lineEdit_aim_app2_file_text.setText(_translate("ObjFmpt2MainForm", "d:/app2.bin"))
        self.pushButton_aim_app2_file_browse.setText(_translate("ObjFmpt2MainForm", "BROWSE"))
        self.pushButton_aim_app2_file_update.setText(_translate("ObjFmpt2MainForm", "UPDATE"))
        self.groupBox_aim_app1.setTitle(_translate("ObjFmpt2MainForm", "APP1 LOAD"))
        self.label_aim_app1_addr.setText(_translate("ObjFmpt2MainForm", "ADDRESS"))
        self.pushButton_aim_app1_addr_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app1_addr_text.setText(_translate("ObjFmpt2MainForm", "0x80001234"))
        self.label_aim_app1_swRel.setText(_translate("ObjFmpt2MainForm", "swRel"))
        self.label_aim_app1_valid.setText(_translate("ObjFmpt2MainForm", "valid"))
        self.pushButton_aim_app1_swRel_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_app1_swRel_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_app1_valid_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app1_swRel_text.setText(_translate("ObjFmpt2MainForm", "0x1234"))
        self.lineEdit_aim_app1_valid_text.setText(_translate("ObjFmpt2MainForm", "0x5678"))
        self.lineEdit_aim_app1_len_text.setText(_translate("ObjFmpt2MainForm", "0x12345678"))
        self.lineEdit_aim_app1_chk_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.label_aim_app1_len.setText(_translate("ObjFmpt2MainForm", "Len"))
        self.pushButton_aim_app1_chk_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.lineEdit_aim_app1_swVer_text.setText(_translate("ObjFmpt2MainForm", "0xABCD"))
        self.pushButton_aim_app1_swVer_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.pushButton_aim_app1_swVer_set.setText(_translate("ObjFmpt2MainForm", "SET"))
        self.pushButton_aim_app1_len_read.setText(_translate("ObjFmpt2MainForm", "READ"))
        self.label_aim_app1_swVer.setText(_translate("ObjFmpt2MainForm", "swVer"))
        self.label_aim_app1_chk.setText(_translate("ObjFmpt2MainForm", "CHECKSUM"))
        self.pushButton_aim_app1_chk_chk.setText(_translate("ObjFmpt2MainForm", "CHK"))
        self.label_aim_app1_file.setText(_translate("ObjFmpt2MainForm", ".BIN FILE"))
        self.lineEdit_aim_app1_file_text.setText(_translate("ObjFmpt2MainForm", "d:/app1.bin"))
        self.pushButton_aim_app1_file_browse.setText(_translate("ObjFmpt2MainForm", "BROWSE"))
        self.pushButton_aim_app1_file_update.setText(_translate("ObjFmpt2MainForm", "UPDATE"))
        self.groupBox_bbo_BatchBurnOperation.setTitle(_translate("ObjFmpt2MainForm", "批量烧录"))
        self.pushButton_bbo_burn_fac_app.setText(_translate("ObjFmpt2MainForm", "BURN FAC/APP LOAD"))
        self.pushButton_bbo_burn_bc_fac_app.setText(_translate("ObjFmpt2MainForm", "BURN BOOTCFG/FAC/APP LOAD"))
        self.lineEdit_bbo_devCode_text.setText(_translate("ObjFmpt2MainForm", "IHU_G2080AQYC_SH001"))
        self.label_bbo_codeFix.setText(_translate("ObjFmpt2MainForm", "devCode"))
        self.lineEdit_bbo_maxNumber_text.setText(_translate("ObjFmpt2MainForm", "100"))
        self.label_bbo_maxNumber.setText(_translate("ObjFmpt2MainForm", "MaxNumber"))
        self.checkBox_bbo_batchModeSelection.setText(_translate("ObjFmpt2MainForm", "批量选定"))
        self.groupBox_cloudCon.setTitle(_translate("ObjFmpt2MainForm", "后台设置"))
        self.lineEdit_cloudCon_label_apply_text.setText(_translate("ObjFmpt2MainForm", "15 SUCCESS, IHU_xxx"))
        self.lineEdit_cloudCon_apply_number_text.setText(_translate("ObjFmpt2MainForm", "15"))
        self.pushButton_cloudCon_par_set.setText(_translate("ObjFmpt2MainForm", "参数设置"))
        self.lineEdit_cloudCon_ipAddr_text.setText(_translate("ObjFmpt2MainForm", "121.40.118.33"))
        self.label_cloudCon_apply_number.setText(_translate("ObjFmpt2MainForm", "applyNumber"))
        self.label_cloudCon_ipAddr.setText(_translate("ObjFmpt2MainForm", "cloudIpAddr"))
        self.lineEdit_cloudCon_facCode_text.setText(_translate("ObjFmpt2MainForm", "FAC#1234"))
        self.label_cloudCon_facCode.setText(_translate("ObjFmpt2MainForm", "facCode"))
        self.lineEdit_cloudCon_pdCode_text.setText(_translate("ObjFmpt2MainForm", "G201"))
        self.label_cloudCon_pdCode.setText(_translate("ObjFmpt2MainForm", "pdCode"))
        self.lineEdit_cloudCon_pjCode_text.setText(_translate("ObjFmpt2MainForm", "AQYC"))
        self.lineEdit_cloudCon_pdType_text.setText(_translate("ObjFmpt2MainForm", "IHU"))
        self.label_cloudCon_pdType.setText(_translate("ObjFmpt2MainForm", "pdType"))
        self.lineEdit_cloudCon_userAccount_text.setText(_translate("ObjFmpt2MainForm", "user123"))
        self.label_cloudCon_userAccount.setText(_translate("ObjFmpt2MainForm", "userAccount"))
        self.lineEdit_cloudCon_passwd_text.setText(_translate("ObjFmpt2MainForm", "user#1234"))
        self.label_cloudCon_passwd.setText(_translate("ObjFmpt2MainForm", "passwd"))
        self.lineEdit_cloudCon_formalFlag_text.setText(_translate("ObjFmpt2MainForm", "Y"))
        self.label_cloudCon_formalFlag.setText(_translate("ObjFmpt2MainForm", "formalFlag"))
        self.pushButton_cloudCon_label_apply.setText(_translate("ObjFmpt2MainForm", "标签申请"))
        self.label_cloudCon_userCode.setText(_translate("ObjFmpt2MainForm", "userCode"))
        self.lineEdit_cloudCon_userCode_text.setText(_translate("ObjFmpt2MainForm", "SH"))
        self.label_cloudCon_pjCode.setText(_translate("ObjFmpt2MainForm", "pjCode"))
        self.groupBox_ihuConn.setTitle(_translate("ObjFmpt2MainForm", "硬板设置"))
        self.pushButton_ihuCon_conn.setText(_translate("ObjFmpt2MainForm", "连接"))
        self.radioButton_ihuCon_port_eth.setText(_translate("ObjFmpt2MainForm", "网口"))
        self.radioButton_ihuCon_port_sps.setText(_translate("ObjFmpt2MainForm", "串口"))
        self.radioButton_ihuCon_port_can.setText(_translate("ObjFmpt2MainForm", "CAN"))
        self.pushButton_ihuCon_disc.setText(_translate("ObjFmpt2MainForm", "断开"))
        self.groupBox_ihuConn_canParSet.setTitle(_translate("ObjFmpt2MainForm", "CAN参数"))
        self.label_ihuConn_canParSet_productType.setText(_translate("ObjFmpt2MainForm", "设备类型"))
        self.comboBox_ihuConn_canParSet_productType.setItemText(0, _translate("ObjFmpt2MainForm", "DEV_USBCAN"))
        self.comboBox_ihuConn_canParSet_productType.setItemText(1, _translate("ObjFmpt2MainForm", "DEV_USBCAN2"))
        self.comboBox_ihuConn_canParSet_index.setItemText(0, _translate("ObjFmpt2MainForm", "0"))
        self.comboBox_ihuConn_canParSet_index.setItemText(1, _translate("ObjFmpt2MainForm", "1"))
        self.comboBox_ihuConn_canParSet_index.setItemText(2, _translate("ObjFmpt2MainForm", "2"))
        self.comboBox_ihuConn_canParSet_index.setItemText(3, _translate("ObjFmpt2MainForm", "3"))
        self.label_ihuConn_canParSet_index.setText(_translate("ObjFmpt2MainForm", "索引号"))
        self.comboBox_ihuConn_canParSet_canNbr.setItemText(0, _translate("ObjFmpt2MainForm", "0"))
        self.comboBox_ihuConn_canParSet_canNbr.setItemText(1, _translate("ObjFmpt2MainForm", "1"))
        self.label_ihuConn_canParSet_canNbr.setText(_translate("ObjFmpt2MainForm", "第几路CAN"))
        self.label_ihuConn_canParSet_rcvCode.setText(_translate("ObjFmpt2MainForm", "验收码0x"))
        self.lineEdit_ihuConn_canParSet_rcvCode_text.setText(_translate("ObjFmpt2MainForm", "80000000"))
        self.lineEdit_ihuConn_canParSet_timer0_text.setText(_translate("ObjFmpt2MainForm", "00"))
        self.label_ihuConn_canParSet_timer0.setText(_translate("ObjFmpt2MainForm", "定时器0: 0x"))
        self.lineEdit_ihuConn_canParSet_maskCode_text.setText(_translate("ObjFmpt2MainForm", "FFFFFFFF"))
        self.label_ihuConn_canParSet_maskCode.setText(_translate("ObjFmpt2MainForm", "屏蔽码0x"))
        self.lineEdit_ihuConn_canParSet_timer1_text.setText(_translate("ObjFmpt2MainForm", "1C"))
        self.label_ihuConn_canParSet_timer1.setText(_translate("ObjFmpt2MainForm", "定时器1: 0x"))
        self.comboBox_ihuConn_canParSet_filter.setItemText(0, _translate("ObjFmpt2MainForm", "全部类型"))
        self.comboBox_ihuConn_canParSet_filter.setItemText(1, _translate("ObjFmpt2MainForm", "只标准帧"))
        self.comboBox_ihuConn_canParSet_filter.setItemText(2, _translate("ObjFmpt2MainForm", "只扩展帧"))
        self.label_ihuConn_canParSet_filter.setText(_translate("ObjFmpt2MainForm", "滤波方式"))
        self.comboBox_ihuConn_canParSet_workMode.setItemText(0, _translate("ObjFmpt2MainForm", "正常"))
        self.comboBox_ihuConn_canParSet_workMode.setItemText(1, _translate("ObjFmpt2MainForm", "只听"))
        self.comboBox_ihuConn_canParSet_workMode.setItemText(2, _translate("ObjFmpt2MainForm", "自测"))
        self.label_ihuConn_canParSet_workMode.setText(_translate("ObjFmpt2MainForm", "工作模式"))
        self.comboBox_ihuConn_canParSet_frameType.setItemText(0, _translate("ObjFmpt2MainForm", "数据帧"))
        self.comboBox_ihuConn_canParSet_frameType.setItemText(1, _translate("ObjFmpt2MainForm", "远程帧"))
        self.label_ihuConn_canParSet_frameType.setText(_translate("ObjFmpt2MainForm", "帧类型"))
        self.comboBox_ihuConn_canParSet_frameFormat.setItemText(0, _translate("ObjFmpt2MainForm", "标准帧"))
        self.comboBox_ihuConn_canParSet_frameFormat.setItemText(1, _translate("ObjFmpt2MainForm", "扩展帧"))
        self.label_ihuConn_canParSet_frameFormat.setText(_translate("ObjFmpt2MainForm", "帧格式"))
        self.label_ihuConn_canParSet_frameId.setText(_translate("ObjFmpt2MainForm", "帧ID 0x"))
        self.lineEdit_ihuConn_canParSet_frameId_text.setText(_translate("ObjFmpt2MainForm", "00100001"))
        self.menu.setTitle(_translate("ObjFmpt2MainForm", "后台设置"))
        self.menu_2.setTitle(_translate("ObjFmpt2MainForm", "硬板设置"))
        self.menu_3.setTitle(_translate("ObjFmpt2MainForm", "控参操作"))
        self.menu_4.setTitle(_translate("ObjFmpt2MainForm", "固件下载"))
        self.menu_5.setTitle(_translate("ObjFmpt2MainForm", "镜像操作"))
        self.menu_6.setTitle(_translate("ObjFmpt2MainForm", "批量烧录"))
        self.menu_7.setTitle(_translate("ObjFmpt2MainForm", "关于"))

