# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fmpt2form.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ObjFmpt2Form(object):
    def setupUi(self, ObjFmpt2Form):
        ObjFmpt2Form.setObjectName("ObjFmpt2Form")
        ObjFmpt2Form.resize(1063, 651)
        self.groupBox_LoadBootcfg = QtWidgets.QGroupBox(ObjFmpt2Form)
        self.groupBox_LoadBootcfg.setGeometry(QtCore.QRect(20, 360, 641, 121))
        self.groupBox_LoadBootcfg.setObjectName("groupBox_LoadBootcfg")
        self.label_CfgFile = QtWidgets.QLabel(self.groupBox_LoadBootcfg)
        self.label_CfgFile.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label_CfgFile.setObjectName("label_CfgFile")
        self.pushButton_LbcBrowse = QtWidgets.QPushButton(self.groupBox_LoadBootcfg)
        self.pushButton_LbcBrowse.setGeometry(QtCore.QRect(550, 40, 75, 23))
        self.pushButton_LbcBrowse.setObjectName("pushButton_LbcBrowse")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_LoadBootcfg)
        self.lineEdit.setGeometry(QtCore.QRect(70, 40, 471, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_LoadBootcfg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 611, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_LbcLoadFile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_LbcLoadFile.setObjectName("pushButton_LbcLoadFile")
        self.horizontalLayout.addWidget(self.pushButton_LbcLoadFile)
        self.pushButton_LbcSaveFile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_LbcSaveFile.setObjectName("pushButton_LbcSaveFile")
        self.horizontalLayout.addWidget(self.pushButton_LbcSaveFile)
        self.pushButton_LbcReadAllFromHw = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_LbcReadAllFromHw.setObjectName("pushButton_LbcReadAllFromHw")
        self.horizontalLayout.addWidget(self.pushButton_LbcReadAllFromHw)
        self.pushButton_LbcWriteAllToHw = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_LbcWriteAllToHw.setObjectName("pushButton_LbcWriteAllToHw")
        self.horizontalLayout.addWidget(self.pushButton_LbcWriteAllToHw)
        self.groupBox_KeyElementOperation = QtWidgets.QGroupBox(ObjFmpt2Form)
        self.groupBox_KeyElementOperation.setGeometry(QtCore.QRect(20, 20, 641, 331))
        self.groupBox_KeyElementOperation.setObjectName("groupBox_KeyElementOperation")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_KeyElementOperation)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 608, 301))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_hwType = QtWidgets.QLabel(self.layoutWidget1)
        self.label_hwType.setMinimumSize(QtCore.QSize(91, 0))
        self.label_hwType.setObjectName("label_hwType")
        self.horizontalLayout_19.addWidget(self.label_hwType)
        self.pushButton_hwType_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_hwType_read.setObjectName("pushButton_hwType_read")
        self.horizontalLayout_19.addWidget(self.pushButton_hwType_read)
        self.pushButton_hwType_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_hwType_write.setObjectName("pushButton_hwType_write")
        self.horizontalLayout_19.addWidget(self.pushButton_hwType_write)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_19.addWidget(self.lineEdit_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_hwPemId = QtWidgets.QLabel(self.layoutWidget1)
        self.label_hwPemId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_hwPemId.setObjectName("label_hwPemId")
        self.horizontalLayout_20.addWidget(self.label_hwPemId)
        self.pushButton_hwPemId_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_hwPemId_read.setObjectName("pushButton_hwPemId_read")
        self.horizontalLayout_20.addWidget(self.pushButton_hwPemId_read)
        self.pushButton_hwPemId_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_hwPemId_write.setObjectName("pushButton_hwPemId_write")
        self.horizontalLayout_20.addWidget(self.pushButton_hwPemId_write)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_20.addWidget(self.lineEdit_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_swRelId = QtWidgets.QLabel(self.layoutWidget1)
        self.label_swRelId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_swRelId.setObjectName("label_swRelId")
        self.horizontalLayout_21.addWidget(self.label_swRelId)
        self.pushButton_swRelId_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swRelId_read.setObjectName("pushButton_swRelId_read")
        self.horizontalLayout_21.addWidget(self.pushButton_swRelId_read)
        self.pushButton_swRelId_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swRelId_write.setObjectName("pushButton_swRelId_write")
        self.horizontalLayout_21.addWidget(self.pushButton_swRelId_write)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_21.addWidget(self.lineEdit_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_swVerId = QtWidgets.QLabel(self.layoutWidget1)
        self.label_swVerId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_swVerId.setObjectName("label_swVerId")
        self.horizontalLayout_22.addWidget(self.label_swVerId)
        self.pushButton_swVerI_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swVerI_read.setObjectName("pushButton_swVerI_read")
        self.horizontalLayout_22.addWidget(self.pushButton_swVerI_read)
        self.pushButton_swVerId_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swVerId_write.setObjectName("pushButton_swVerId_write")
        self.horizontalLayout_22.addWidget(self.pushButton_swVerId_write)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_22.addWidget(self.lineEdit_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_swUpgradeFlag = QtWidgets.QLabel(self.layoutWidget1)
        self.label_swUpgradeFlag.setMinimumSize(QtCore.QSize(91, 0))
        self.label_swUpgradeFlag.setObjectName("label_swUpgradeFlag")
        self.horizontalLayout_23.addWidget(self.label_swUpgradeFlag)
        self.pushButton_swUpgradeFlag_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swUpgradeFlag_read.setObjectName("pushButton_swUpgradeFlag_read")
        self.horizontalLayout_23.addWidget(self.pushButton_swUpgradeFlag_read)
        self.pushButton_swUpgradeFlag_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swUpgradeFlag_write.setObjectName("pushButton_swUpgradeFlag_write")
        self.horizontalLayout_23.addWidget(self.pushButton_swUpgradeFlag_write)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_23.addWidget(self.lineEdit_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_swUpgPollId = QtWidgets.QLabel(self.layoutWidget1)
        self.label_swUpgPollId.setMinimumSize(QtCore.QSize(91, 0))
        self.label_swUpgPollId.setObjectName("label_swUpgPollId")
        self.horizontalLayout_24.addWidget(self.label_swUpgPollId)
        self.pushButton_swUpgPollId_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swUpgPollId_read.setObjectName("pushButton_swUpgPollId_read")
        self.horizontalLayout_24.addWidget(self.pushButton_swUpgPollId_read)
        self.pushButton_swUpgPollId_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swUpgPollId_write.setObjectName("pushButton_swUpgPollId_write")
        self.horizontalLayout_24.addWidget(self.pushButton_swUpgPollId_write)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_24.addWidget(self.lineEdit_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_bootIndex = QtWidgets.QLabel(self.layoutWidget1)
        self.label_bootIndex.setMinimumSize(QtCore.QSize(91, 0))
        self.label_bootIndex.setObjectName("label_bootIndex")
        self.horizontalLayout_25.addWidget(self.label_bootIndex)
        self.pushButton_bootIndex_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_bootIndex_read.setObjectName("pushButton_bootIndex_read")
        self.horizontalLayout_25.addWidget(self.pushButton_bootIndex_read)
        self.pushButton_bootInde_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_bootInde_write.setObjectName("pushButton_bootInde_write")
        self.horizontalLayout_25.addWidget(self.pushButton_bootInde_write)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_25.addWidget(self.lineEdit_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_bootAreaMax = QtWidgets.QLabel(self.layoutWidget1)
        self.label_bootAreaMax.setMinimumSize(QtCore.QSize(91, 0))
        self.label_bootAreaMax.setObjectName("label_bootAreaMax")
        self.horizontalLayout_26.addWidget(self.label_bootAreaMax)
        self.pushButton_bootAreaMax_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_bootAreaMax_read.setObjectName("pushButton_bootAreaMax_read")
        self.horizontalLayout_26.addWidget(self.pushButton_bootAreaMax_read)
        self.pushButton_bootAreaMax_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_bootAreaMax_write.setObjectName("pushButton_bootAreaMax_write")
        self.horizontalLayout_26.addWidget(self.pushButton_bootAreaMax_write)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_26.addWidget(self.lineEdit_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_cipherKey = QtWidgets.QLabel(self.layoutWidget1)
        self.label_cipherKey.setMinimumSize(QtCore.QSize(91, 0))
        self.label_cipherKey.setObjectName("label_cipherKey")
        self.horizontalLayout_27.addWidget(self.label_cipherKey)
        self.pushButton_cipherKey_read = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cipherKey_read.setObjectName("pushButton_cipherKey_read")
        self.horizontalLayout_27.addWidget(self.pushButton_cipherKey_read)
        self.pushButton_cipherKey_write = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cipherKey_write.setObjectName("pushButton_cipherKey_write")
        self.horizontalLayout_27.addWidget(self.pushButton_cipherKey_write)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_27.addWidget(self.lineEdit_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.groupBox_OperationLogInfo = QtWidgets.QGroupBox(ObjFmpt2Form)
        self.groupBox_OperationLogInfo.setGeometry(QtCore.QRect(20, 490, 641, 111))
        self.groupBox_OperationLogInfo.setObjectName("groupBox_OperationLogInfo")
        self.textEdit_OprLogInfo = QtWidgets.QTextEdit(self.groupBox_OperationLogInfo)
        self.textEdit_OprLogInfo.setGeometry(QtCore.QRect(10, 20, 621, 81))
        self.textEdit_OprLogInfo.setObjectName("textEdit_OprLogInfo")

        self.retranslateUi(ObjFmpt2Form)
        self.pushButton_hwType_read.clicked.connect(ObjFmpt2Form.slotKeoHwTypeRead)
        self.pushButton_hwType_write.clicked.connect(ObjFmpt2Form.slotKeoHwTypeWrite)
        self.pushButton_hwPemId_read.clicked.connect(ObjFmpt2Form.slotKeoHwPemIdRead)
        self.pushButton_hwPemId_write.clicked.connect(ObjFmpt2Form.slotKeoHwPemIdWrite)
        self.pushButton_swRelId_read.clicked.connect(ObjFmpt2Form.slotKeoSwRelIdRead)
        self.pushButton_swRelId_write.clicked.connect(ObjFmpt2Form.slotKeoSwRelIdWrite)
        self.pushButton_swVerI_read.clicked.connect(ObjFmpt2Form.slotKeoSwVerIdRead)
        self.pushButton_swVerId_write.clicked.connect(ObjFmpt2Form.slotKeoSwVerIdWrite)
        self.pushButton_swUpgradeFlag_read.clicked.connect(ObjFmpt2Form.slotKeoSwUpgFlagRead)
        self.pushButton_swUpgradeFlag_write.clicked.connect(ObjFmpt2Form.slotKeoSwUpgFlagWrite)
        self.pushButton_swUpgPollId_read.clicked.connect(ObjFmpt2Form.slotKeoSwUpgPollIdRead)
        self.pushButton_swUpgPollId_write.clicked.connect(ObjFmpt2Form.slotKeoSwUpgPollIdWrite)
        self.pushButton_bootIndex_read.clicked.connect(ObjFmpt2Form.slotKeoBootIndexRead)
        self.pushButton_bootInde_write.clicked.connect(ObjFmpt2Form.slotKeoBootIndexWrite)
        self.pushButton_bootAreaMax_read.clicked.connect(ObjFmpt2Form.slotKeoBootAreaMaxRead)
        self.pushButton_bootAreaMax_write.clicked.connect(ObjFmpt2Form.slotKeoBootAreaMaxWrite)
        self.pushButton_cipherKey_read.clicked.connect(ObjFmpt2Form.slotKeoCipherKeyRead)
        self.pushButton_cipherKey_write.clicked.connect(ObjFmpt2Form.slotKeoCipherKeyWrite)
        self.pushButton_LbcBrowse.clicked.connect(ObjFmpt2Form.slotLbcBrowse)
        self.pushButton_LbcLoadFile.clicked.connect(ObjFmpt2Form.slotLbcLoadFile)
        self.pushButton_LbcSaveFile.clicked.connect(ObjFmpt2Form.slotLbcSaveFile)
        self.pushButton_LbcReadAllFromHw.clicked.connect(ObjFmpt2Form.slotLbcReadFromHw)
        self.pushButton_LbcWriteAllToHw.clicked.connect(ObjFmpt2Form.slotLbcWriteToHw)
        QtCore.QMetaObject.connectSlotsByName(ObjFmpt2Form)
        ObjFmpt2Form.setTabOrder(self.pushButton_hwType_read, self.pushButton_hwType_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_hwType_write, self.lineEdit_10)
        ObjFmpt2Form.setTabOrder(self.lineEdit_10, self.pushButton_hwPemId_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_hwPemId_read, self.pushButton_hwPemId_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_hwPemId_write, self.lineEdit_11)
        ObjFmpt2Form.setTabOrder(self.lineEdit_11, self.pushButton_swRelId_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_swRelId_read, self.pushButton_swRelId_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_swRelId_write, self.lineEdit_12)
        ObjFmpt2Form.setTabOrder(self.lineEdit_12, self.pushButton_swVerI_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_swVerI_read, self.pushButton_swVerId_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_swVerId_write, self.lineEdit_13)
        ObjFmpt2Form.setTabOrder(self.lineEdit_13, self.pushButton_swUpgradeFlag_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_swUpgradeFlag_read, self.pushButton_swUpgradeFlag_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_swUpgradeFlag_write, self.lineEdit_14)
        ObjFmpt2Form.setTabOrder(self.lineEdit_14, self.pushButton_swUpgPollId_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_swUpgPollId_read, self.pushButton_swUpgPollId_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_swUpgPollId_write, self.lineEdit_15)
        ObjFmpt2Form.setTabOrder(self.lineEdit_15, self.pushButton_bootIndex_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_bootIndex_read, self.pushButton_bootInde_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_bootInde_write, self.lineEdit_16)
        ObjFmpt2Form.setTabOrder(self.lineEdit_16, self.pushButton_bootAreaMax_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_bootAreaMax_read, self.pushButton_bootAreaMax_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_bootAreaMax_write, self.lineEdit_17)
        ObjFmpt2Form.setTabOrder(self.lineEdit_17, self.pushButton_cipherKey_read)
        ObjFmpt2Form.setTabOrder(self.pushButton_cipherKey_read, self.pushButton_cipherKey_write)
        ObjFmpt2Form.setTabOrder(self.pushButton_cipherKey_write, self.lineEdit_18)
        ObjFmpt2Form.setTabOrder(self.lineEdit_18, self.lineEdit)
        ObjFmpt2Form.setTabOrder(self.lineEdit, self.pushButton_LbcBrowse)
        ObjFmpt2Form.setTabOrder(self.pushButton_LbcBrowse, self.pushButton_LbcLoadFile)
        ObjFmpt2Form.setTabOrder(self.pushButton_LbcLoadFile, self.pushButton_LbcSaveFile)
        ObjFmpt2Form.setTabOrder(self.pushButton_LbcSaveFile, self.pushButton_LbcReadAllFromHw)
        ObjFmpt2Form.setTabOrder(self.pushButton_LbcReadAllFromHw, self.pushButton_LbcWriteAllToHw)
        ObjFmpt2Form.setTabOrder(self.pushButton_LbcWriteAllToHw, self.textEdit_OprLogInfo)

    def retranslateUi(self, ObjFmpt2Form):
        _translate = QtCore.QCoreApplication.translate
        ObjFmpt2Form.setWindowTitle(_translate("ObjFmpt2Form", "FMPT2"))
        self.groupBox_LoadBootcfg.setTitle(_translate("ObjFmpt2Form", "LOAD BOOTCFG"))
        self.label_CfgFile.setText(_translate("ObjFmpt2Form", "CFG FILE"))
        self.pushButton_LbcBrowse.setText(_translate("ObjFmpt2Form", "BROWSE"))
        self.lineEdit.setText(_translate("ObjFmpt2Form", "C:\\boot\\a.cfg"))
        self.pushButton_LbcLoadFile.setText(_translate("ObjFmpt2Form", "LOAD FILE"))
        self.pushButton_LbcSaveFile.setText(_translate("ObjFmpt2Form", "SAVE FILE"))
        self.pushButton_LbcReadAllFromHw.setText(_translate("ObjFmpt2Form", "READ ALL FROM HARDWARE"))
        self.pushButton_LbcWriteAllToHw.setText(_translate("ObjFmpt2Form", "WRITE ALL TO HARDWARE"))
        self.groupBox_KeyElementOperation.setTitle(_translate("ObjFmpt2Form", "KEY ELEMENT OPERATION"))
        self.label_hwType.setText(_translate("ObjFmpt2Form", "hwType"))
        self.pushButton_hwType_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_hwType_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_10.setText(_translate("ObjFmpt2Form", "0x1234"))
        self.label_hwPemId.setText(_translate("ObjFmpt2Form", "hwPemId"))
        self.pushButton_hwPemId_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_hwPemId_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_11.setText(_translate("ObjFmpt2Form", "0x1234"))
        self.label_swRelId.setText(_translate("ObjFmpt2Form", "swRelId"))
        self.pushButton_swRelId_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_swRelId_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_12.setText(_translate("ObjFmpt2Form", "0x1234"))
        self.label_swVerId.setText(_translate("ObjFmpt2Form", "swVerId"))
        self.pushButton_swVerI_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_swVerId_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_13.setText(_translate("ObjFmpt2Form", "0x1234"))
        self.label_swUpgradeFlag.setText(_translate("ObjFmpt2Form", "swUpgradeFlag"))
        self.pushButton_swUpgradeFlag_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_swUpgradeFlag_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_14.setText(_translate("ObjFmpt2Form", "0x12"))
        self.label_swUpgPollId.setText(_translate("ObjFmpt2Form", "swUpgPollId"))
        self.pushButton_swUpgPollId_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_swUpgPollId_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_15.setText(_translate("ObjFmpt2Form", "0x12"))
        self.label_bootIndex.setText(_translate("ObjFmpt2Form", "bootIndex"))
        self.pushButton_bootIndex_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_bootInde_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_16.setText(_translate("ObjFmpt2Form", "0x12"))
        self.label_bootAreaMax.setText(_translate("ObjFmpt2Form", "bootAreaMax"))
        self.pushButton_bootAreaMax_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_bootAreaMax_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_17.setText(_translate("ObjFmpt2Form", "0x12"))
        self.label_cipherKey.setText(_translate("ObjFmpt2Form", "cipherKey"))
        self.pushButton_cipherKey_read.setText(_translate("ObjFmpt2Form", "READ"))
        self.pushButton_cipherKey_write.setText(_translate("ObjFmpt2Form", "WRITE"))
        self.lineEdit_18.setText(_translate("ObjFmpt2Form", "0x12345678"))
        self.groupBox_OperationLogInfo.setTitle(_translate("ObjFmpt2Form", "OPERATION LOG INFO"))
        self.textEdit_OprLogInfo.setHtml(_translate("ObjFmpt2Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; SND 0x1111 to Hardware</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; RCV 0x2222 from Hardware</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt; ERR info get from reading file</p></body></html>"))

