# Generated by Django 2.1a1 on 2018-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF3dm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='co1',
            field=models.FloatField(default=0, verbose_name='一氧化碳'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='h2s',
            field=models.FloatField(default=0, verbose_name='硫化氢'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='hcho',
            field=models.FloatField(default=0, verbose_name='酒精'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='lightstr',
            field=models.FloatField(default=0, verbose_name='光照'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='no1',
            field=models.FloatField(default=0, verbose_name='一氧化氮'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='pwrind',
            field=models.FloatField(default=0, verbose_name='电量强度'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='rssi',
            field=models.FloatField(default=0, verbose_name='信号强度'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='so2',
            field=models.FloatField(default=0, verbose_name='二氧化硫'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='toxicgas',
            field=models.FloatField(default=0, verbose_name='煤气'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='co1',
            field=models.FloatField(default=0, verbose_name='一氧化碳'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='h2s',
            field=models.FloatField(default=0, verbose_name='硫化氢'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='hcho',
            field=models.FloatField(default=0, verbose_name='酒精'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='lightstr',
            field=models.FloatField(default=0, verbose_name='光照'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='no1',
            field=models.FloatField(default=0, verbose_name='一氧化氮'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='pwrind',
            field=models.FloatField(default=0, verbose_name='电量强度'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='rssi',
            field=models.FloatField(default=0, verbose_name='信号强度'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='so2',
            field=models.FloatField(default=0, verbose_name='二氧化硫'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='toxicgas',
            field=models.FloatField(default=0, verbose_name='煤气'),
        ),
    ]
