# Generated by Django 2.1a1 on 2018-09-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF2cm', '0002_auto_20180927_1133'),
        ('DappDbF3dm', '0002_auto_20180912_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f3dm_current_report_smartcity',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('tsp', models.FloatField(default=0, verbose_name='TSP')),
                ('pm01', models.FloatField(default=0, verbose_name='PM0.1')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10')),
                ('noise', models.FloatField(default=0, verbose_name='噪声')),
                ('temperature', models.FloatField(default=0, verbose_name='温度')),
                ('humidity', models.FloatField(default=0, verbose_name='湿度')),
                ('winddir', models.FloatField(default=0, verbose_name='风向')),
                ('windspd', models.FloatField(default=0, verbose_name='风速')),
                ('lightstr', models.FloatField(default=0, verbose_name='光照强度')),
                ('lampmode', models.IntegerField(default=0, verbose_name='灯带工作模式')),
                ('dev_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_device_inventory')),
                ('site_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_site_common')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f3dm_minute_report_smartcity',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(auto_now=True)),
                ('hourminindex', models.IntegerField(default=0)),
                ('tsp', models.FloatField(default=0, verbose_name='TSP')),
                ('pm01', models.FloatField(default=0, verbose_name='PM0.1')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10')),
                ('noise', models.FloatField(default=0, verbose_name='噪声')),
                ('temperature', models.FloatField(default=0, verbose_name='温度')),
                ('humidity', models.FloatField(default=0, verbose_name='湿度')),
                ('winddir', models.FloatField(default=0, verbose_name='风向')),
                ('windspd', models.FloatField(default=0, verbose_name='风速')),
                ('lightstr', models.FloatField(default=0, verbose_name='光照强度')),
                ('lampmode', models.IntegerField(default=0, verbose_name='灯带工作模式')),
                ('dev_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_device_inventory')),
                ('site_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_site_common')),
            ],
        ),
    ]
