# Generated by Django 2.1.4 on 2019-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF3dm', '0002_dct_t_l3f3dm_day_report_aqyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='no2',
            field=models.FloatField(default=0, verbose_name='二氧化氮'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_day_report_aqyc',
            name='no2',
            field=models.FloatField(default=0, verbose_name='二氧化氮'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_hour_report_aqyc',
            name='no2',
            field=models.FloatField(default=0, verbose_name='二氧化氮'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f3dm_minute_report_aqyc',
            name='no2',
            field=models.FloatField(default=0, verbose_name='二氧化氮'),
        ),
    ]
