<<<<<<< HEAD
# Generated by Django 2.0.2 on 2019-04-12 10:10
=======
# Generated by Django 2.1.7 on 2019-04-11 19:37
>>>>>>> 19deb93d02253bb66ca311399129f52699254c5e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF3dm', '0002_dct_t_l3f3dm_day_report_aqyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f2cm_nbiot_ctc_token',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('appid', models.CharField(max_length=256)),
                ('appsecret', models.CharField(max_length=256)),
                ('serviceid', models.CharField(max_length=256)),
                ('accesstoken', models.CharField(max_length=256)),
                ('refreshtoken', models.CharField(max_length=256)),
                ('accexpires', models.DateTimeField(max_length=0)),
                ('refexpires', models.DateTimeField(max_length=0)),
            ],
        ),
    ]
