# Generated by Django 2.1.1 on 2018-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF3dm', '0003_dct_t_l3f3dm_current_report_smartcity_dct_t_l3f3dm_minute_report_smartcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f3dm_current_report_aqyc',
            name='cmd_flag',
            field=models.CharField(default='00', max_length=2, verbose_name='信号标志位'),
        ),
    ]
