'''
Created on Mar 29, 2018

@author: hitpony
'''

import random
import sys
import time
import json
import os
import re
import urllib
import http
import socket



#Gllbal set data
GL_FAWS_RFID_KB_EVENT_ID = 0;
GL_FAWS_SPS_READ_VALUE = 0;
GL_FAWS_RFID_READ_VALUE = 0;
GL_FAWS_RFID_INPUT_FLAG = 0;
GL_FAWS_GLOBAL_CNT = 0;
GL_FAWS_GLOBAL_RPI_FLAG = 0;


#CLOUD SERVER INFO
GL_FAWS_CLOUDCON_PAR_APPLY_NUMBER_SET_DEFAULT = 1;
GL_FAWS_CLOUDCON_PAR_APPLY_NUMBER_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_APPLY_NUMBER_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_IP_ADDR_SET_DEFAULT = "120.55.125.100";
GL_FAWS_CLOUDCON_PAR_IP_ADDR_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_IP_ADDR_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_FAC_CODE_SET_DEFAULT = "FAC#123";
GL_FAWS_CLOUDCON_PAR_FAC_CODE_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_FAC_CODE_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_PD_CODE_SET_DEFAULT = "G201";
GL_FAWS_CLOUDCON_PAR_PD_CODE_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_PD_CODE_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_PJ_CODE_SET_DEFAULT = "GTJY";
GL_FAWS_CLOUDCON_PAR_PJ_CODE_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_PJ_CODE_SET_DEFAULT;
GL_FAWS_HUITP_IEID_UNI_EQULABEL_APPLY_USER_INFO_HCU = 1;
GL_FAWS_HUITP_IEID_UNI_EQULABEL_APPLY_USER_INFO_IHU = 2;
GL_FAWS_CLOUDCON_PAR_PD_TYPE_SET_DEFAULT = GL_FAWS_HUITP_IEID_UNI_EQULABEL_APPLY_USER_INFO_IHU;
GL_FAWS_CLOUDCON_PAR_PD_TYPE_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_PD_TYPE_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_USER_CODE_SET_DEFAULT = "SH";
GL_FAWS_CLOUDCON_PAR_USER_CODE_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_USER_CODE_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_USER_ACCOUNT_SET_DEFAULT = "user1234";
GL_FAWS_CLOUDCON_PAR_USER_ACCOUNT_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_USER_ACCOUNT_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_PASSWD_SET_DEFAULT = "user#1234";
GL_FAWS_CLOUDCON_PAR_PASSWD_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_PASSWD_SET_DEFAULT;
GL_FAWS_CLOUDCON_PAR_FORMAL_FLAG_DEFAULT = "Y";
GL_FAWS_CLOUDCON_PAR_FORMAL_FLAG_SET_BY_USER = GL_FAWS_CLOUDCON_PAR_FORMAL_FLAG_DEFAULT;
GL_FAWS_CLOUDCON_HUITP_LOCAL_DEVID_DEFAULT = "IHU_G1200FAWS_SH001"; #"HCU_G1210FAWS_RND01";
GL_FAWS_CLOUDCON_HUITP_SVR_NAME_DEFAULT = "XHZN";
GL_FAWS_CLOUDCON_HUITP_MSG_FORMAT = "huitp-json";
GL_FAWS_CLOUDCON_HUITP_JSON_PORT = '9516';
GL_FAWS_HUITP_IEID_UNI_EQULABLE_INSERVICE_INFO_START = 1;
GL_FAWS_HUITP_IEID_UNI_EQULABLE_INSERVICE_INFO_STOP = 2;
GL_FAWS_HUITP_IEID_UNI_EQULABLE_INSERVICE_INFO_SET = GL_FAWS_HUITP_IEID_UNI_EQULABLE_INSERVICE_INFO_START;

#FAWS互联网+秤
GL_FAWS_HUITP_JSON_MSGID_uni_faws_data_report           = 0x5D80;
GL_FAWS_HUITP_JSON_MSGID_uni_faws_data_confirm          = 0x5D00;



class MyClass(object):
    '''
    classdocs
    '''


    def __init__(self, params):
        '''
        Constructor
        '''
        
