# Generated by Django 2.1a1 on 2018-08-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DappDbF1sym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_common',
            fields=[
                ('dev_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('socket_id', models.IntegerField(blank=True, null=True)),
                ('hw_type', models.IntegerField(blank=True, null=True)),
                ('hw_ver', models.IntegerField(blank=True, null=True)),
                ('sw_rel', models.IntegerField(blank=True, null=True)),
                ('sw_ver', models.IntegerField(blank=True, null=True)),
                ('sw_update', models.IntegerField(default=0, null=True)),
                ('db_update', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_favour_site',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_key_auth_fhys',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('authlevel', models.CharField(max_length=1)),
                ('authobj', models.IntegerField(default=0)),
                ('authtype', models.CharField(max_length=1)),
                ('validnum', models.IntegerField(default=0)),
                ('validstart', models.DateField(null=True)),
                ('validend', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_pg_common',
            fields=[
                ('pg_code', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=20)),
                ('pg_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_common',
            fields=[
                ('prj_code', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=20)),
                ('prj_creator', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_site_common',
            fields=[
                ('site_code', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=20)),
                ('site_creator', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=2, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('superintendent', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(max_length=15, null=True)),
                ('site_area', models.FloatField(blank=True, default=0, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_virtual_key_fhys',
            fields=[
                ('keyid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('keyname', models.CharField(max_length=20)),
                ('ownerid', models.CharField(max_length=15, null=True)),
                ('ownername', models.CharField(max_length=20, null=True)),
                ('keystatus', models.CharField(max_length=1)),
                ('keytype', models.CharField(max_length=1)),
                ('hwcode', models.CharField(max_length=50)),
                ('memo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_aqyc',
            fields=[
                ('dev_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DappDbF2cm.dct_t_l3f2cm_device_common')),
                ('status', models.CharField(max_length=2, null=True)),
                ('ip_addr', models.GenericIPAddressField(null=True)),
                ('mac_addr', models.CharField(max_length=20, null=True)),
                ('cam_url', models.CharField(max_length=100, null=True)),
                ('ctrl_url', models.CharField(max_length=100, null=True)),
                ('ctrl_port', models.IntegerField(default=0, null=True)),
                ('rtsp_port', models.IntegerField(default=0)),
                ('service_port', models.IntegerField(default=0)),
                ('ssh_port', models.IntegerField(default=0)),
                ('vnc_port', models.IntegerField(default=0)),
                ('nvr_web_port', models.IntegerField(default=0)),
                ('nvr_rstp_port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_fstt',
            fields=[
                ('dev_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DappDbF2cm.dct_t_l3f2cm_device_common')),
                ('cam_url', models.CharField(max_length=100)),
                ('ctrl_url', models.CharField(max_length=100)),
                ('ctrl2_port', models.IntegerField(blank=True, null=True)),
                ('rtsp2_port', models.IntegerField(blank=True, null=True)),
                ('ctrl3_port', models.IntegerField(blank=True, null=True)),
                ('rtsp3_port', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_aqyc',
            fields=[
                ('prj_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DappDbF2cm.dct_t_l3f2cm_project_common')),
                ('eng_code', models.CharField(max_length=50)),
                ('eng_name', models.CharField(blank=True, max_length=50, null=True)),
                ('prj_type', models.IntegerField(default=0)),
                ('prj_category', models.IntegerField(default=0)),
                ('prj_period', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=5)),
                ('region', models.IntegerField(default=0)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('contractors', models.CharField(blank=True, max_length=50, null=True)),
                ('eng_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('site_area', models.FloatField(blank=True, null=True)),
                ('building_area', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=2, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=0)),
                ('eng_status', models.BooleanField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_project_fstt',
            fields=[
                ('prj_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DappDbF2cm.dct_t_l3f2cm_project_common')),
            ],
        ),
        migrations.CreateModel(
            name='dct_t_l3f2cm_site_fstt',
            fields=[
                ('site_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DappDbF2cm.dct_t_l3f2cm_site_common')),
                ('order_no', models.CharField(max_length=10)),
                ('tower_sn', models.CharField(max_length=10)),
                ('tower_code', models.CharField(max_length=15)),
                ('tower_type', models.IntegerField(blank=True, default=0)),
                ('tower_conf', models.IntegerField(blank=True, default=0)),
                ('tower_date', models.DateField(blank=True, default=0)),
                ('install_date', models.DateTimeField(auto_now=True)),
                ('lamp_start', models.TimeField(default='00:00:00', null=True)),
                ('lamp_stop', models.TimeField(default='00:00:00', null=True)),
                ('lamp_mode', models.IntegerField(default=0, null=True)),
                ('snr_light', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_virtual_key_fhys',
            name='prj_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_project_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_site_common',
            name='prj_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_project_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_project_common',
            name='pg_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DappDbF2cm.dct_t_l3f2cm_pg_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_key_auth_fhys',
            name='keyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_virtual_key_fhys'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_favour_site',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_site_common'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_favour_site',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF1sym.dct_t_l3f1sym_account_primary'),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_common',
            name='site_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_site_common'),
        ),
        migrations.AlterIndexTogether(
            name='dct_t_l3f2cm_virtual_key_fhys',
            index_together={('keytype',)},
        ),
    ]
