# Generated by Django 2.1a1 on 2018-09-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF2cm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dct_t_l3f2cm_device_cail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dust_coefmax', models.FloatField(default=700)),
                ('dust_coefmin', models.FloatField(default=10)),
                ('dust_coefK', models.FloatField(default=1)),
                ('dust_coefB', models.FloatField(default=0)),
                ('dust_threshold', models.FloatField(default=30)),
                ('temp_coefmax', models.FloatField(default=100)),
                ('temp_coefmin', models.FloatField(default=-40)),
                ('temp_coefK', models.FloatField(default=1)),
                ('temp_coefB', models.FloatField(default=0)),
                ('humid_coefmax', models.FloatField(default=100)),
                ('humid_coefmin', models.FloatField(default=0)),
                ('humid_coefK', models.FloatField(default=1)),
                ('humid_coefB', models.FloatField(default=0)),
                ('noise_coefmax', models.FloatField(default=130)),
                ('noise_coefmin', models.FloatField(default=30)),
                ('noise_coefK', models.FloatField(default=1)),
                ('noise_coefB', models.FloatField(default=0)),
                ('windspd_coefmax', models.FloatField(default=35)),
                ('windspd_coefmin', models.FloatField(default=0)),
                ('windspd_coefK', models.FloatField(default=1)),
                ('windspd_coefB', models.FloatField(default=0)),
                ('winddir_coefmax', models.FloatField(default=360)),
                ('winddir_coefmin', models.FloatField(default=0)),
                ('winddir_coefK', models.FloatField(default=1)),
                ('winddir_coefB', models.FloatField(default=0)),
                ('winddir_delta', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='dust_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='dust_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='dust_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='dust_coefmin',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='dust_threshold',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='humid_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='humid_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='humid_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='humid_coefmin',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='noise_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='noise_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='noise_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='noise_coefmin',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='temp_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='temp_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='temp_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='temp_coefmin',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='winddir_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='winddir_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='winddir_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='winddir_coefmin',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='winddir_delta',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='windspd_coefB',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='windspd_coefK',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='windspd_coefmax',
        ),
        migrations.RemoveField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='windspd_coefmin',
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_holops',
            name='cmd_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_holops',
            name='prjid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_holops',
            name='prjname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='cus_info',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_site_fstt',
            name='lamp_th',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f2cm_project_common',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f2cm_site_common',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_cail',
            name='dev_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DappDbF2cm.dct_t_l3f2cm_device_inventory'),
        ),
    ]
