# Generated by Django 2.1.1 on 2018-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DappDbF2cm', '0002_auto_20180927_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_cail',
            name='dust_cannon',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='dct_t_l3f2cm_device_fstt',
            name='socket_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dct_t_l3f2cm_device_inventory',
            name='zhb_label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
